### ISSUE TITLE
Einstellungen bitte in die App selbst

### ISSUE THREAD

**Issue by LocutusB** [remuslazar/EVPlugFinderPublic#1]
Hallo, 

die persönlichen Einstellungen, insbesondere welche Steckertypen vom eigenen EV unterstützt werden, fände ich direkt in der App besser aufgehoben. 
Z.B. interessieren mich CEE Stecker nicht immer. In einer "Notsituation" würde ich mir die auf die Schnelle aber gerne einblenden.
Die Bezeichnungen CEE 7/4 und CEE 3 Pin sind mir nicht geläufig. Hier würde ich eher CEE Blau 16A, CEE Rot 16A und CEE Rot 32A verwenden. Schuko und Type F würde ich einen eigenen Filter spendieren. Ebenso die Bezeichnung Mennekes (Type 2) finde ich eigenartig. Ich würde Typ 2 schreiben und den ursprünglichen Hersteller Mennekes max. in Klammern dahinter. Evtl. auch hier noch die Unterscheidung in die Leistungsklassen 11kW, 22kW oder 43kW.

Gruß
Philipp

**Comment by remuslazar** [comment]
@LocutusB danke fürs Feedback!

### Settings

Ja, ich habe die Settings so gemacht weil ich dachte, das muss man eh nur einmal einstellen. Aber ich verstehe die Problematik. Eventuell kann man das in der Tat über einen neuen Filter lösen, sodass man leichter „Schuko und alles <16A“ ausblendet, weil das eigentlich gar keinen Sinn macht, wenn man nicht in einer absoluten Not-Situation ist. Ich werde hier ein Paar Sachen ausprobieren.

### Bezeichnungen

Die Bezeichnungen nehme ich momentan direkt aus der Datenbank:

http://api.openchargemap.io/v2/referencedata/

Allerdings filtere ich die Liste, damit nicht zu viele Anschlüsse angezeigt werden, welche hier in DE eh keine Rolle spielen. Aber das ist eine gute Idee, ich kann die Typen auch lokalisieren, dann kann man für Deutsch eben andere, schönere Namen verwenden, welche auch „übersetzbar" sind.

**Comment by secuder** [comment]
Zwei Anmerkungen zu diesem "Issue":
Settings: Ohne den Hinweis hier hätte ich die Einstellungen gar nicht besucht. :-)
Bezeichnungen: die "lokalisierten" Bezeichnungen wie von LocutusB vorgeschlagen finde ich griffiger

**Comment by remuslazar** [comment]
@LocutusB ich habe nun einige Issues erstellt für einige Punkte, die hier genannt wurden, daher werde ich dieses Issue erst mal schließen.

Die ursprünglich Idee, die App Settings in der App zu verwalten möchte ich nicht weiter verfolgen, und das aus zwei Gründen:

1) Alles, was man in der App Settings konfiguriert ist eigentlich als "Setup and Forget" gedacht. Welche Steckertypen das eigene Auto unterstützt ändert sich höchstens nach einem Auto-Kauf und ist nicht etwas, was man immer wieder im laufenden Betrieb machen muss.
2) ein zusätzlicher Knopf wird die UX unnötig "aufblähen"

Ich denke aber, sobald #4 implementiert ist, kann man mit diesem Filter das gewünschte erreichen, ohne dass man dafür die App Settings "mißbraucht".
