### ISSUE TITLE
Improvement for tour planning

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#10]
The APP offers all charging points in the vicinity. For tour planning it might be helpfull to search for a city or - more important - a small village.
This would influence the appereance of the APP, if on the main screen - but maybe somewhere else?

**Comment by remuslazar** [comment]
@secuder yes, this is somehow also related to #7. I agree, having a generic search feature will be kinda cool.. I will think about it, thanks!

**Comment by remuslazar** [comment]
implemented in Build 10
