### ISSUE TITLE
Störung wird nicht als behoben angezeigt

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#102]
Wie lange dauert es, bis eine auf der GE-Webseite als behoben eingetragene Störung diesen Status auch in der APP bekommt? Auch nach Neustart der APP ist die Ladesäule noch gestört, im Web ist sie als "in Ordnung" angezeigt: [Ladesäule Landratsamt SW](https://www.goingelectric.de/stromtankstellen/Deutschland/Schweinfurt/Landratsamt-Schrammstrasse-3/11284/)

**Comment by secuder** [comment]
![e6586f8d-c1a5-4aa9-974e-1073f3fb248f](https://user-images.githubusercontent.com/24484266/34169478-d5552fa4-e4e7-11e7-81b0-8646581bcf01.png)
![70a0d4a8-4050-4ba2-8417-5f82c686e688](https://user-images.githubusercontent.com/24484266/34169480-d589db8c-e4e7-11e7-8171-a8709e8004c6.png)

**Comment by secuder** [comment]
![image](https://user-images.githubusercontent.com/24484266/34169575-23f5ec8e-e4e8-11e7-8cea-8fd988846b64.png)

**Comment by remuslazar** [comment]
der Abgleich findet mehrfach täglich statt, mit einer bestimmten Heuristik. Spätestens am nächsten Tag sind die Daten synchron. Das lässt sich anders technisch nicht realisieren, weil GE in die Richtung keinerlei Schnittstellen anbietet..

**Comment by secuder** [comment]
dann passt ja alles :)
