### ISSUE TITLE
Bessere Erklärung AC-Schnellader (>= 22kw)

### ISSUE THREAD

**Issue by stinnux** [remuslazar/EVPlugFinderPublic#104]
Ich denke die Option bedarf etwas mehr Erklärung. 

ich fahre (bald) einen Ioniq, der kann zwar mit 32A aber nur 1phasig laden. Also maximal 7,4kw.

Muss ich nun den Haken setzen oder nicht? Und was genau bewirkt der Haken?

**Comment by remuslazar** [comment]
Du hast es im Prinzip schon beantwortet. Da 7,4kW < 22kW solltest du den Schalter nicht aktivieren. Das bewirkt, dass für dich geeignete Ladestationen als Schnellladestationen klassifiziert werden und so z.B. die 22kW AC Ladestationen lediglich als „medium“ power eingestuft werden, diese werden auch durch den Schnellladefilter nicht erfasst. Dagegen siehst du die Aldi 20kW DC Lader grün.

**Comment by remuslazar** [comment]
Die Hilfe wurde bereits in die Richtung überarbeitet, ist aber aus verschiedenen Gründen noch nicht live. Sobald dies der Fall sein wird, kann man hier eine Neubewertung vornehmen, ob in die Richtung noch Erklärungsbedarf besteht oder nicht.

**Comment by remuslazar** [comment]
@stinnux was meinst du, passt nun die Erklärung in der neuen Hilfe? Sollte man hier noch was anpassen?

**Comment by stinnux** [comment]
Ja, ich finde es so viel besser und verständlicher. Danke fürs Ändern (und überhaupt für die Arbeit die du dir machst)
