### ISSUE TITLE
Trennung Anzahl Ladestationen / Radius

### ISSUE THREAD

**Issue by stinnux** [remuslazar/EVPlugFinderPublic#105]
Ich finde die Option sehr verwirrend, da sie zwei Einstellungen in einem beinhaltet und man nicht erkennen kann welchen Wert man nun eingestellt hat.

Ich fände es besser unterschiedliche Slider einzublenden, je nachdem welche Datenquelle gewählt wurde. Eventuell ist es dazu notwendig die Einstellung unterhalb des Datenquelle-Menüs einzublenden.

**Comment by remuslazar** [comment]
Ja, das wurde bereits vorgeschlagen, ist aber technisch nicht realisierbar. Die App-Settings müssen statisch sein, da kann man keine Logik implementieren.

**Comment by stinnux** [comment]
Mach doch zwei getrennte Einstellungen draus und Pack die ins Datenquellen-Menü.

**Comment by remuslazar** [comment]
Das sollte eine globale Einstellung bleiben, Datenquellen-agnostik sozusagen. Wenn ich mich entschieden habe, möglichst viele Ladestationen auf einmal anzuzeigen (z.B. iPad Pro), so will ich das für beide Datenquellen gleichermaßen nutzen. Macht auch keinen Sinn, 2 Slider anzubieten, die dann exakt das gleiche einstellen, oder? Warum sollte man das überhaupt getrennt einstellen können?

**Comment by stinnux** [comment]
Naja, einmal stellst du einen Radius ein und einmal eine maximale Anzahl. Ich finde das hat jetzt nicht allzuviel miteinander zu tun. Aber klar, ist deine Entscheidung.

Schöne fände ich noch wenn man die tatsächlichen Werte sehen würde.

**Comment by remuslazar** [comment]
Ja, das ist halt eine Besonderheit der jew. Registry. Ich fände es auch besser, wenn man auch mit einem Radius bei OCM suchen könnte, das ist aber technisch nicht aktuell so implementiert.

Eigentlich ist es einfach: siehst du zu viele Ladestationen auf einmal? Slider nach links. Zu wenige? Dann nach rechts. Egal ob das mit dem Radius oder mit "max" gearbeitet wird, das sollte dem User eigentlich egal sein, auch der aktuelle Wert ist nicht relevant.
Und das lässt sich auch nicht so umsetzen, wie ich bereits erwähnt habe, die Settings müssen komplett _statisch_ sein. Da kann man auch kein Label dynamisch ändern oder sowas.

**Comment by remuslazar** [comment]
@stinnux ich habe nun darüber nachgedacht und ich gebe dir Recht, dass die aktuelle Beschreibung in der Hilfe aktuell verwirrend ist. Ich habe das im #109 festgehalten. Danke!
