### ISSUE TITLE
Ladestrom Preisberechnung / Preis API 

### ISSUE THREAD

**Issue by F3000** [remuslazar/EVPlugFinderPublic#107]
Hast du die bestimmt auch schon Gedanken dazu gemacht . Wenn ich den Beitrag übersehen habe bitte löschen :) 

- Integration von aktuellen Preisen 
- Berechnung der Gesamtkosten für eine tank Füllung -> hierfür ein neues Eingabefeld erstellen wo man die Kapazität des Akkus angeben kann oder Fahrzeeugmodell Auswahl (ersteres wird einfacher sein )

**Comment by remuslazar** [comment]
Ja, das habe ich schon gelesen, in die Richtung ist nichts geplant. Ich finde das auch nicht so ein "Killer-Feature", da sind andere Dinge wie z.B. Car-Play und Routenberechnung wichtiger als die Kosten..

Außerdem scheitert das schon im Ansatz, weil ja momentan keine API gibt, wo man aktuelle Preise her bekommt.. Und außerdem ist ja je nach Ladekarte und Tarif eine komplexe Matrix, die dann raus kommt.

Ich persönlich halte auch nicht viel davon, der E-Mobilist von heute fährt doch nicht elektrisch, um Kosten zu sparen.. mag sein, dass sich das in Zukunft ändern wird, aber, wie gesagt.. aktuell gibt es meinerseits 0 Ambitionen, dies anzugehen:)

**Comment by stinnux** [comment]
Ich fände das schon interessant ob ich an der Ladesäule von allego in 10km Entfernung für 0,69 € pro kwh laden muss oder 20km weiter fahre und dort vielleicht eine Ladesäule habe bei dir ich mit der Entega-Flat zahlen kann. 

Ich bin jetzt kein Pfennigfuchser, aber ich gebe ungern unnötiges Geld aus. 

Aber wie du schon sagst fehlt es dazu an den notwendigen Datenquellen. Die Matrix macht mir jetzt nicht soviel sorgen.

Ich hoffe da aber auf den Gesetzgeber, der hoffentlich mal Ordnung in das Chaos bringt.

**Comment by remuslazar** [comment]
Die Matrix ist auch kein Problem per se, ist aber in der Erfassung schon recht anspruchsvoll, das wollte ich damit ausdrücken. Es reich ja nich zu sagen, ich habe die Ladekarten X,Y und Z sondern man muss ja pro Ladekarte auch die Optionen angeben können, die dann auch noch Laufzeiten haben uvw. Der ganze Wartungsaufwand ist auch nicht unerheblich, bei den Benzinpreisen ist dagegen schon eher "Kindergeburtstag", wenn man das so vergleicht. Aber, wie gesagt, das wird schon im Ansatz scheitern, ganz einfach deshalb, weil die Anbieter gar keine große Lust haben werden, die Kosten transparent zur Verfügung zu stellen. Allego will ja sicher nicht, dass der potentielle Kunde da 10km weiter fährt. Und wo kein Wille ist, so wird auch die API nicht kommen!

tl;dr

Die Diskussion auf GoingElectric habe ich auch mitverfolgt. Nichts für ungut, ich gehöre aber eindeutig zu der Fraktion die eine Regulierung wie auch immer ablehnen. Die Infrastruktur wird lange nicht kostendeckend zu betreiben sein. Wenn man die Hürde höher setzt, so geht der Schuss gewaltig nach hinten los. Die Diskussion gehört aber nicht hierher, wollte aber nur mal gesagt haben:) Gerne mehr dazu im GE Forum....

**Comment by F3000** [comment]
Alles klar . Danke für deine Erläuterung :) 

Aber ja , CarPlay und Route ist wichtiger
