### ISSUE TITLE
Filter und Einstellungen trennen

### ISSUE THREAD

**Issue by stinnux** [remuslazar/EVPlugFinderPublic#108]
Ich finde es verwirrend das sich der Menüpunkt für die Einstellungen im Filtermenü befindet. Ich würde das trennen. 

Außerdem würde ich die Auswahl der Ladekarten in die Einstellungen verschieben. 

Die Liste der Karten kommt vermutlich von GE und lässt sich nicht weiter filtern, oder? Zum Beispiel nach "Physische Karte notwendig" oder "Voranmeldung notwendig" oder ähnlichem?

**Comment by remuslazar** [comment]
@stinnux das geht nicht, wie ich schon sagte, die Settings müssen statisch sei, die Ladekarten werden zur Laufzeit aktualisiert. Deswegen ist das so wie es ist.

Die Liste der Karten kommt von GE, richtig, dort gibt es außer den Namen und die entsprechende ID keine weiteren Infos.
