### ISSUE TITLE
Anzahl Ladestationen Slider: Footer Text

### ISSUE THREAD

**Issue by remuslazar** [remuslazar/EVPlugFinderPublic#109]
## Einleitung

Mit dem Slider soll der User die Anzahl der Ladestationen, die bei einem Request angezeigt werden, einstellen können. Technisch wird das jedoch, je nach Registry, unterschiedlich implementiert:

* bei GoingElectric kann man nur einen Radius angeben
* bei OCM kann man nur mit einem sog. "Limit" arbeiten

um diese Anzahl zu steuern.

Also steuert diese Einstellung (Slider-Value) das eine oder andere, um das gewünschte Ziel zu erreichen.

## Status Quo

Aktuell wird darauf eingegangen und auch die Min/Max Werte dort im Footer Text entsprechend beschrieben. Dies ist kontraproduktiv und für den Benutzer verwirrend, siehe auch #105.

## Neuer Footer Text

Aus diesem Grunde sollte man diese "Implementierungsdetails" verbergen und dem Benutzer dort eine einfache Botschaft übermitteln, sinngemäß:

_"Hier kannst du die Anzahl der Ladestationen anpassen. Hast du ein iPad und willst mehrere Ladestationen auf einmal sehen, bewege den Slider nach rechts. Bist du mit einem kleinen iPhone unterwegs und möchtest du eine möglichst hohe Performance bei schlechter Netzabdeckung haben? Bewege den Slider nach links."_

Die Details, dass bei GE mit dem Radius gearbeitet wird und wie das genau bei der jew. Registry implementiert ist, sollte man besser in der Hilfe verankern, z.B. im FAQ-Bereich oder dort wo die Settings erklärt werden. Dort kann man diese Details für den interessierten/Power-User zur Verfügung stellen.

Relates #105

**Comment by Wordcrafts** [comment]
Wenn wir dann aus dem Section Label noch das " /Radius" rauswerfen, könnte man den Text so gestalten:

"Stelle die Anzahl der gleichzeitig dargestellten Ladestationen ein. Auf kleinen Geräten (iPhone SE) oder bei schlechter Internetverbindung ist ein geringer Wert (eher links) empfehlenswert, auf größeren Geräten oder iPads sind größere Werte sinnvoll (eher rechts)."

**Comment by remuslazar** [comment]
@Wordcrafts klingt gut. Ich brauche es noch für Englisch, dann hätten wir's!

**Comment by remuslazar** [comment]
@Wordcrafts willst du dann auch in die Hilfe eine ggf. detailliertere Beschreibung aufnehmen? Also erklären, dass je nach Registry mit limit oder Radius gearbeitet wird und auch weshalb etc. Im Prinzip das, was aktuell im Settings zu lesen ist in einer ggf. besseren Form.

**Comment by Wordcrafts** [comment]
EN:
"Configure how many charging stations are displayed. On small devices like the iPhone SE or when internet connection is poor, use a smaller number (slider to the left). On devices with a bigger screen (including iPad) chargEV benefits from greater values (slider to the right).

**Comment by Wordcrafts** [comment]
Bzgl. Hilfe-Text: Ja, aber schaffe ich nicht mehr vor dem Release heute. Eher am Sonntag der Montag. Aber die Hilfe ist ja zum Glück nicht im App-Bundle :)
