### ISSUE TITLE
iPad: Absturz bei Auswahl der Einstellungen

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#11]
Neues Fenster / Hinweis auf Settings wurde an meinem iPad sofort überlagert von der "anderen" Einstellungsfrage, ob die APP auf die Ortsinformation zugreifen darf. Nach Beantwortung dieser Frage war dann das erste Fenster wieder zu sehen. Geht, ist aber unschön :-)

Die Auswahl von "Einstellungen" resultierte in einem Absturz der APP. 

Die Einstellungen ließen sich danach normal aufrufen und bedienen, auch die APP funktioniert nun normal.

Auf dem iPhone passierte das nicht, hier war zuvor schon die Vorgängerversion installiert, deshalb kam wohl auch die Frage nach der Verwendung der Ortsinformation nicht.

Der Hinweistext war nicht zu lang und damit auch nicht zu aufdringlich, aber ich habe ihn auch nicht allzulang gelesen oder drüber nachgegrübelt. Wenn ich das soll, bitte den Text hier noch mal einstellen.

**Comment by remuslazar** [comment]
@secuder komisch, normalerweise kriege ich das ja mit via TestFlight. Offensichtlich ist aber die App dabei nicht abgestürzt oder da ist was anderes passiert, sodass auch kein Crashlog erstellt werden konnte. Weird.. Ist die App wirklich abgestürzt oder war sie einfach im Hintergrund, während die Einstellungen aufgerufen wurden?

![bildschirmfoto 2016-12-12 um 21 27 42](https://cloud.githubusercontent.com/assets/6108134/21115534/0fa14022-c0b2-11e6-859a-3f388592c5bb.png)

**Comment by secuder** [comment]
Was da wirklich passiert ist, kann ich Dir leider nicht beantworten. Jedenfalls waren auch die Einstellungen _nicht_ im Vordergrund. Und auch keine andere App.

**Comment by remuslazar** [comment]
@secuder ok, ich konnte das reproduzieren! Danke!
