### ISSUE TITLE
Integration mit Waze

### ISSUE THREAD

**Issue by X2921294H** [remuslazar/EVPlugFinderPublic#111]
Hi remus,
hattest Du ggf. schon einmal überlegt den EVPlugFinder mit waze zu integrieren?
Bzw. die Möglichkeit anzubieten Suchergebnisse an waze zu übertragen?
VG

**Comment by remuslazar** [comment]
Ich kenne wenige Leute, die auf Waze schwören - ich persönlich nutze es nicht. Um ehrlich zu sein, habe ich es schon mal kurzzeitig installiert, ich konnte mich aber mit der verspielten UX nicht anfreunden, sodass das ein "no go" Kriterium (für mich) war. Daher meine Antwort: nein und nein :)

**Comment by X2921294H** [comment]
Schade … aber Danke für Dein offenes und ehrliches Feedback.

Von: Remus Lazar [mailto:notifications@github.com]
Gesendet: Montag, 5. Februar 2018 19:12
An: remuslazar/EVPlugFinderPublic <EVPlugFinderPublic@noreply.github.com>
Cc: Süß, Patrick <SuessP@telekom.de>; Author <author@noreply.github.com>
Betreff: Re: [remuslazar/EVPlugFinderPublic] Integration mit Waze (#111)


Ich kenne wenige Leute, die auf Waze schwören - ich persönlich nutze es nicht. Um ehrlich zu sein, habe ich es schon mal kurzzeitig installiert, ich konnte mich aber mit der verspielten UX nicht anfreunden, sodass das ein "no go" Kriterium (für mich) war. Daher meine Antwort: nein und nein :)
