### ISSUE TITLE
Feature: ""Anstupsen"

### ISSUE THREAD

**Issue by IPSCoyote** [remuslazar/EVPlugFinderPublic#112]
Feature Wunsch:

In der App kann man ja einen CheckIn an Ladesäulen machen. Wie wäre es, wenn man in der App sein Kennzeichen hinterlegen könnte. So könnten die User einander in der App "anstupsen" (z.B. wenn man fertig geladen hat, aber die Säule noch blockiert). Siehe die wohl eingestellte App "ChargeBump".

Ich finde das eine solche Funktion immer wichtiger wird (bei steigender BEV Zahl). Und warum dann die Funktion nicht in der einen App haben, die man für die Säulensuche verwendet.

(ok... ich müsste 2 Kennzeichen hinterlegen können ;))

**Comment by F3000** [comment]
+1

**Comment by remuslazar** [comment]
Interessante Idee. Ich bin mir nicht sicher, ob das langfristig Sinn macht, das löst eigentlich nur ein Symptom. Das darunterlegende Problem sind einfach zu wenig (Destination Charging) Ladepunkte.

Bei einem Schnelllader wird man ja i.d.R. nicht länger als 20-30 Minuten verweilen, so ist ja die Wartezeit im Schnitt ca. 10 Minuten. Also wäre das eher für Destination Charging interessant, dass man einander "abstöpseln" könnte, richtig?

@IPSCoyote kannst du mal ein Use-Case beschreiben, wann du die App nutzen würdest und welche Vorteile für dich und andere dabei siehst? Bzw. wie du dir eine solche Funktion in der App vorstellen könntest?

Ich werde auch mal die besagte App installieren und einmal das durchspielen.

### ChargeBump Link

https://itunes.apple.com/uz/app/chargebump/id978352478?mt=8
