### ISSUE TITLE
Display of matching Charging Cards for chosen charging station when set a filter

### ISSUE THREAD

**Issue by ikemuc** [remuslazar/EVPlugFinderPublic#113]
Idea for improvement of this great app:
When I set a filter for the charging cards I have, I want to see, which of my charging cards works for a charging station I have selected in the map. Currently it seems to show the "owning" operator only, which isn't interesting for me, if I set a filter to my cards. (The information seems to be available as the filter works.)
This would increase my trust before I drive to the charging station, that I can really load.

Example:
When I search charging stations in Meran, Italy with a filter set to Newmotion and Plugsurfing (App and Key), I see the station in "4.November Str.", which really works for me (I've loaded there already), but when I look at the information, it shows "Alperia" only. If it would show me "Newmotion" instead of Alperia (or additionally), I would trust this information much more :-)

**Comment by remuslazar** [comment]
This sounds interesting but unfortunately there is no Going Electric API endpoint to get this kind of information (matching chargecards for a specific charging station) nor is this info included in the JSON payload for the particular charging station details.

Technically you can just provide a set of charge cards id while performing the search, this will filter out charge points which are not compatible with the given set of chargecards.

**Comment by ikemuc** [comment]
Hm, good point... Are you in contact with the Going Electric developers? Maybe they could add this information, as this is really valuable for users?
Other option would be to query Going Electric for each selected card separately and then combine the result sets in the app, then the app would have the information. But especially with many selected charging networks, this wouldn't be "server friendly" as the number of queries multiplies. But you could limit this algorithm to like 5 charging networks... :-)

**Comment by remuslazar** [comment]
@ikemuc currently there are quite a few feature requests open since many months there, e.g.:

https://www.goingelectric.de/forum/goingelectric-stromtankstellen/offizielle-api-t20221-50.html#p512422

and others.

To be honest, I don't think that there will be any add-ons to the API soon.

Your suggested workaround, performing 5x more API calls for every single request is not a viable solution, sorry.

**Comment by ikemuc** [comment]
Hm, then maybe you could add a possibility to your app that I can add "my charge cards" out of the very long list of known charge cards and when I set the filter, I can choose from MY cards only. This would make it easier to change the filter quickly to see the charging stations for e.g. newmotion?

**Comment by remuslazar** [comment]
indeed, I agree. There are already some discussions going on in other places (Slack) about this kind of feature, I will synthesize the good ideas and create a new issue for.
