### ISSUE TITLE
App crash while navigating to the CheckIns list view

### ISSUE THREAD

**Issue by remuslazar** [remuslazar/EVPlugFinderPublic#114]
## Abstract

App crashes while trying to view the checkin list for some charging stations.

## How to reproduce

1. Search for the location "SI Suites" and select the first hit (this should be "Plieninger Straße 101").
2. Open the detail view of the charging point named "SI Suites" near-by
3. Tap on the Check-In table row to open the list view

The App crashes!

## Technical

The root cause is a bug in the JavaScript code handling the synchronization of the CheckIns <> "Ladelogs" from the GE Registry. In some cases, the logic creates CheckIn records with an invalid timestamp and reason code. The app currently does not handle that (the app assumes that the data is valid) and catch this kind of errors with a trap, crashing.

## ToDo's

* Fix the JavaScript Code (ge-tools project)
* Implement a test case to avoid regressions
* Fix all broken existing records in the production CloutKit Environment
* Charge the App logic so the app handles this kind of situations (e.g. while ignoring checkins with invalid/inconsistent data)

**Comment by Wordcrafts** [comment]
Does not crash for me.

**Comment by remuslazar** [comment]
Affected CheckIns:

```
CheckIn without timestamp found for chargepoint chargepoint-0-19219 (reason: 100).
CheckIn without timestamp found for chargepoint chargepoint-0-16150 (reason: 100).
CheckIn without timestamp found for chargepoint chargepoint-0-25263 (reason: 100).
CheckIn without timestamp found for chargepoint chargepoint-0-26961 (reason: 100).
```

Affected chargepoints:

```
Missmatch found: chargepoint-0-25263 (100/1970-01-01T00:00:00.000Z) does not match last checkIn C8AD9949-8C62-4CEC-8470-A886D3745872 (10/2018-01-13T05:21:57.895Z)
Missmatch found: chargepoint-0-19219 (100/1970-01-01T00:00:00.000Z) does not match last checkIn 0E30D5C6-5952-4366-BD68-5E2BF0465A70 (10/2018-01-16T05:26:07.702Z)
Missmatch found: chargepoint-0-16150 (100/1970-01-01T00:00:00.000Z) does not match last checkIn B4AC3896-5E45-41F8-A86A-FB1B9E5316CC (10/2017-12-04T05:21:45.985Z)
Missmatch found: chargepoint-0-26961 (100/1970-01-01T00:00:00.000Z) does not match last checkIn DF5E6E18-5F88-4FB7-8C79-3081C3D9B5E3 (10/2018-01-31T13:43:06.552Z)
```
