### ISSUE TITLE
smatrics Ladenetz nicht auswählbar

### ISSUE THREAD

**Issue by dakoal** [remuslazar/EVPlugFinderPublic#115]
Man kann in den Einstellungen/Karten nur zwei smatrics mit „Alt“ markierte Lade-Karten wählen, dann sind aber in der Landkarte alle als „smatrics“ markierten Lader weg.

**Comment by remuslazar** [comment]
Die App nutzt die Karteninfos und auch Zuordnung von GoingElectric. Vermutlich ist in diesem Falle die Zuordnung falsch, oder man muss andere Karten nutzen, um diese Lader nutzen zu können.

Siehe auch: https://www.goingelectric.de/stromtankstellen/

**Comment by dakoal** [comment]
Die Auswahl ändert sich auch nicht wenn man "Open Charge Map" auswählt. Wenn ich aber einen Ladepunkt anwähle steht Ladenetz "smatrics", also muss es ja irgendwo hinterlegt sein.

**Comment by remuslazar** [comment]
bei OCM hat der Filter gar keine Funktion - die Notion von Ladekarten und Filterung kennt die OCM API nicht.

Es ist schon irgendwo hinterlegt und zwar in der GoingElectric Datenbank. Die App nutzt die GoingElectric API und Filterung, um die Ladestationen anzuzeigen. Sobald dort die Zuordnung korrigiert ist, wird die App das auch sofort korrekt visualisieren.

Bitte einfach im GoingElectric Forum dafür ein Thread aufmachen und fragen, warum man mit den Ladekarten X,Y nicht bei Ladepunkt Z laden kann:

https://www.goingelectric.de/forum/ladesaeulen-status/

Sollte es sich um einen Fehler handeln, so sind dort auch die Leute unterwegs, welche das korrigieren können.

**Comment by dakoal** [comment]
THX for the info.

Ich werde auf goingelectric nachbohren.
