### ISSUE TITLE
GE: Fehlerhafte HTML-Entities

### ISSUE THREAD

**Issue by premultiply** [remuslazar/EVPlugFinderPublic#122]
Hier z. B. im Feld **Kosten**
https://www.goingelectric.de/stromtankstellen/Deutschland/Frankfurt-am-Main/Bleidenstrasse-Bleidenstrasse-6-7/488/

Darstellung in der App:
![img_2968](https://user-images.githubusercontent.com/4681172/37251952-8b2899e4-2519-11e8-8258-6f5ded9c0ff3.PNG)

Darstellung auf der Webseite:
![img_2969](https://user-images.githubusercontent.com/4681172/37251953-8f5290b0-2519-11e8-9db7-88fdb8531e97.jpg)

**Comment by remuslazar** [comment]
Die HTML Entities werden grundsätzlich dekodiert, z.B. „Ladeweile etc.“. Bei Kosten offensichtlich nicht, das ist schon ein Bug. Ich werde bei der Gelegenheit alle Text-Felder durchgehen und ggf. das Decoding vornehmen. Danke!
