### ISSUE TITLE
Suche nach Taufkirchen gibt falsches Ergebnis

### ISSUE THREAD

**Issue by apographon** [remuslazar/EVPlugFinderPublic#123]
Hallo, eine Suche nach Taufkirchen Vils zeigt das korrekte Ergebnis in der Trefferliste, die Auswahl von Taufkirchen Vils bringt mich dann aber nach München-Taufkirchen. ;-)

**Comment by remuslazar** [comment]
@apographon ich kann das nicht nachvollziehen, siehe Screenshots.

## Suche

<img width="467" alt="image" src="https://user-images.githubusercontent.com/6108134/40709250-de1bf446-63f5-11e8-99a4-479cdc979851.png">

## Auswahl

<img width="467" alt="image" src="https://user-images.githubusercontent.com/6108134/40709278-ee2041a8-63f5-11e8-8a8e-cb5c77b068e3.png">

Wenn das bei dir anders ist, bräuchte ich mehr Infos (evtl. Screenshots, wie oben), um das Problem besser eingrenzen zu können.
