### ISSUE TITLE
Filterbeschriftung "nur DC-Schnelllader"

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#13]
Filterbeschriftung "nur DC-Schnelllader" ist inhaltlich falsch: Es werden auch AC Ladepunkte gefunden.

(Bei OpenCargeMap zB der Crowdfunding Ladepunkt in Würzburg mit 43kW AC, 
bei GE sind bereits 22kW Lader Schnelllader - und davon gibt es eine Menge mit AC).

Unabhängig von dem Filternamen:
Die Eigenschaft "Schnelllader" wird offenbar in den beiden Datenbanken unterschiedlich interpretiert (GE 22kW+, OpenChargeMap 40kW+). Keine Ahnung, wie das lösbar ist oder transparent gemacht werden kann.

(unabhängig von der komplizierten Frage, ab welcher kW-Leistung ein Ladepunkt für den USER als Schnelllader zählt)

**Comment by remuslazar** [comment]
@secuder bei "DC only" werden aber nur DC Stationen gesucht. Klar, wenn die Station auch AC Ladepunkte hat, so werden diese auch angezeigt, aber ich gehe davon aus, dass die Station auch mind. 1x DC haben muss (was zu der Filtereinstellung passt), sonst kann ich es mir nicht erklären, warum das angezeigt wird. Geht es hier um GE oder OCM? Bei Open Charge Map wird eine andere Condition eingesetzt, bei GE ist das so, wie ich oben beschrieben habe.

Kann ich mal die URL des Ladepunktes haben, wo das falsch ist, damit ich das reproduzieren kann?

**Comment by secuder** [comment]
Redest Du über die Einstellungen (DC) oder über den Filter? Der Filter zeigt definitiv auch reine AC Stationen an, sowohl bei GE als auch bei OCM.

GE:
[http://www.goingelectric.de/stromtankstellen/Deutschland/Schweinfurt/elektro-Buehler-Ernst-Sachs-Strasse-94-96/13722/](url)
OCM:
[http://openchargemap.org/site/poi/addcomment/54113](url) - hier gibt es allerdings den Eintrag 0x0 kW (1A) CHAdeMO, also DC ist im Datenbankeintrag genannt, aber mit 0x und vor allem auch der Ladeleistung 0kW - zumindest letzteres erfüllt nicht das Schnellladekriterium :-) (dennoch wohl Datenbankfehler)

Wenn Du die Anzahl der Filterschieber nicht erhöhen willst: Ich fände es ungünstig, wenn mit dem Filter alle AC Stationen ausgefiltert würde (insbesondere bei der GE Datenbank). Ob das USER-Auto AC oder DC verträgt, wird in den (Grund-)Einstellungen festgelegt, der Filter sollte daran nicht mehr herumdoktern, sondern nur über die Ladeleistung filtern.

**Comment by remuslazar** [comment]
@secuder das kann ich aber so nicht nachvollziehen, habe explizit mit der GE Registry nach dem o.g. Eintrag gesucht. Ich hänge auch mal 2 Screenshots rein zum nachvollziehen
![bildschirmfoto 2016-12-13 um 10 49 22](https://cloud.githubusercontent.com/assets/6108134/21135383/fee8e896-c121-11e6-847f-1bbb74d72cba.png)
![bildschirmfoto 2016-12-13 um 10 48 44](https://cloud.githubusercontent.com/assets/6108134/21135384/ff08d43a-c121-11e6-8659-e005fd0e8d14.png)

**Comment by secuder** [comment]
Hallo @remuslazar 
hat sich mit der neuen Version eh erledigt, oder?

Bei mir war das definitiv so. Was hattest Du in den Einstellungen gewählt? Hattest Du Typ 2 "erlaubt"? Falls nein wäre das unterschiedliche Verhalten erklärt.

**Comment by remuslazar** [comment]
@secuder so waren diese eingestellt, als ich die Screenshots gemacht habe:

![bildschirmfoto 2016-12-13 um 19 01 52](https://cloud.githubusercontent.com/assets/6108134/21152498/b7572480-c166-11e6-83f9-7d57462bdaf5.png)

**Comment by secuder** [comment]
das sind aber doch schon die Einstellungen der neuen Version...?

**Comment by remuslazar** [comment]
nein, aber so wie sie gesetzt sind waren früher (wo diese Settings nicht gab) default. Aber nun egal, würde ich sagen, wenn es mit der neuen Version funktioniert, dann muss man das nicht weiter durch deklinieren.

**Comment by secuder** [comment]
Ha, lustig: Du siehst es im Video, das ich hochgeladen habe: In Kassel gibt es da drei Schnelllader, der linke davon hat kein DC
(sorry, ich lass das Thema jetzt auch...)

**Comment by remuslazar** [comment]
@secuder nee, ich will das schon verstehen, warum das passiert:) Also ich fasse es zusammen:

1. Die Option "AC Fast charging" bei "EV Capabilities" ist _nicht_ aktiviert
2. Filter "Nur Schnelllader" ist aktiv
3. Es werden trotzdem Ladestationen angezeigt, die kein DC haben

Falls das so ist, bitte die ID oder die URL in GE der Ladestation durchgeben, dann kann ich das debuggen.

**Comment by secuder** [comment]
nee, das war die **vorletzte** Version oder so, da gab es den "AC fast charging" noch gar nicht.
(bzw. eventuell im Hintergrund, aber für mich als User nicht). Deshalb dachte ich, es sei auch nicht mehr wichtig.
Jedenfalls:
Einstellungen waren: Typ2+Schuko+CEE on
die Einstellungen "Schnellladeleistung" und "AC Schnelllader" gab es noch nicht
Filter "Nur Schnelllader" aktiv
Es wurden Ladestationen angezeigt, die kein DC haben

**Comment by remuslazar** [comment]
ältere Versionen spielen erst mal keine Rolle, würde ich sagen. Also wenn das mit der neuste Version immer noch nicht funktioniert, dann schaue ich es mir an. Ansonsten .. close() :)
