### ISSUE TITLE
Links to GoingElectric opens privacy statement (since update 16.8.2018)

### ISSUE THREAD

**Issue by IPSCoyote** [remuslazar/EVPlugFinderPublic#134]
If open going electric information to a charging station (the "I" button), I'm forwarded to the privacy statement of going electric and I'm stocked (iPhone X). This happens with the last update of ChargEV.

To reproduce:
- Open ChargeV (latest update from 16.8.2018)
- Selecte any charging station
- in the Details click on the "I" next to "Going Electric" (Datasource)
- Privacy Statement of GE is shown

Remark: I use the "privacy mode" in safari.

**Comment by remuslazar** [comment]
@IPSCoyote the privacy URL being opened in Safari, you have to touch the upper left icon to return to the (in background running) chargEV application:

![image](https://user-images.githubusercontent.com/6108134/42806525-f25977d8-89ae-11e8-9b0b-8a7ec886deaf.png)

**Comment by IPSCoyote** [comment]
Thanks for the fast reply.

Coming back is not the issue. I want to see the going electric information on the charging station (like before). The privacy statement should not occur at all at this place.

I expect a page like 
https://www.goingelectric.de/stromtankstellen/Deutschland/Neustadt-a-d-Aisch/Jobcenter-Hans-Boeckler-Strasse-3/28502/
