### ISSUE TITLE
Tesla Superchargers are displayed even when not selected

### ISSUE THREAD

**Issue by below** [remuslazar/EVPlugFinderPublic#140]
I don’t have Superchargers selected in the settings, but they are still shown

**Comment by remuslazar** [comment]
This is not a bug, the issue being caused by the fact that the superchargers do also have CCS plugs. Try to use the chargecards filter, this should filter out the SuCs.

**Comment by Wordcrafts** [comment]
However, this is something to keep in mind for future versions, @remuslazar, as we cannot assume anymore than CCS in general is available for everybody.
