### ISSUE TITLE
Zoom "Regeln"

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#15]
Es bleibt dem USER unklar, warum bei Filterbetätigung die Karte raus und reinzoomt (wahrscheinlich Anzahl der Ladepunkte, scheint mir aber nicht immer die gleiche Anzahl zu sein)

Der "hier bin ich Punkt" ist oft außerhalb der Mitte; auch schon gleich zu Beginn - evtl. weil die Ladepunkte unsymmetrisch um den Ortspunkt liegen.

Ich weiß nicht, ob das ein Problem ist oder den USER nur wundert.

**Comment by remuslazar** [comment]
@secuder so ist das zur Zeit, ja, nachdem die Punkte geladen werden, zoomt die Karte automatisch, um alle Punkte darstellen zu können.
