### ISSUE TITLE
Filter-Knopf hängt

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#16]
Wenn man den Knopf "nur DC-Schnelllader" drückt und dann recht schnell diesen Filter wieder ausschalten will, dann hängt der Knopf häufiger mal.
(Werden da Daten nachgeladen?)

**Comment by remuslazar** [comment]
@secuder hmm, das kann ich nicht nachvollziehen. Daten werden geladen, ja, aber in einem Background-Thread asynchron, das sollte die GUI nicht beeinträchtigen. Kann mir höchstens vorstellen, wenn das iPhone sonst auch schwer "am kämpfen" ist und wenig RAM hat, dass er dann Dinge auslagern muss in dem Moment. Aber das geht eigentlich bei iOS auch recht flüssig auch mit älterer Hardware..  Vielleicht testweise andere Apps schließen, damit man das als Fehlerursache ausschließen kann? Hier konnte ich das weder im Simulator noch auf einem echten Gerät nachvollziehen. Werden dabei viele Punkte geladen? Evtl. 2-3 Screenshots machen, damit ich das besser nachvollziehen kann.

Ich lasse das erst mal offen.

**Comment by secuder** [comment]
Das ist ein iPad Air 2, mit etwas mehr als 4GB frei

(Vielleicht bin ich zu blöd zum tippen - kann es sein, dass nur der linke Teil des Schiebeschalters aktiv auf den Finger wartet, unabhängig von der Schalterstellung? Dann isses mein Fehler...)

Video:

[https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAbRQ1ngcCyfODvKY_J06wP5fJCXZAQrIlB4tRfhNpVnEvunhckLKuAeN%2F%24%7Bf%7D%3Fo%3DAud2bawJnbBugrGn3gOGB3Vf3sXqBJxElfRvYTbZWG8I%26v%3D1%26x%3D3%26a%3DBVHA2ykgT6bdA0tsOAEA_wHIAP8tGSjF%26e%3D1484168320%26k%3D%24%7Buk%7D%26fl%3D%26r%3DD17598FA-E574-4522-94B5-F7014A6658B6-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DF910F500-0EB3-4685-987A-A73774117F74%26p%3D45%26s%3DK-l9AMcwQebk8cPOzC1EDa7NOAc&uk=72JMCQCTy1oWHXthaxegeg&f=IMG_3343.MOV&sz=55628524](url)

**Comment by remuslazar** [comment]
@secuder danke für das Video! Ach ja, jetzt sehe ich es. Vermute ein Problem mit den Touch Events. Das ist vermutlich eine Regression aus #6. Normalerweise ist es so, dass solche Popups modal angezeigt werden und man außerhalb klicken muss, um es zu schließen und damit die darunter liegende View wieder in der Responder-Kette eingehängt wird. Das habe ich nun geändert.

Vielleicht schalte ich das im nächsten Build mal aus, damit man dieses Problem besser eingrenzen kann. Ich bleibe dran, danke nochmals!

**Comment by remuslazar** [comment]
@secuder kannst du bitte prüfen, ob das mit dem neusten Build immer noch so in der Form auftritt? Ich kann das nicht reproduzieren, weder im Simulator noch auf dem Gerät.

**Comment by secuder** [comment]
Sieht okay aus
