### ISSUE TITLE
Verschieben des Ergebnisfensters

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#18]
Beim Verschieben der Karte werden keinen neuen Ladepunkte nachgeladen. Dazu muss erst der Reload Knopf gedrückt werden. Das ist für den USER gewöhnungsbedürftig.

**Comment by remuslazar** [comment]
ja, ich wollte aber die Last auf die API möglichst minimal halten und nicht dauernd requests machen, wie der User die Karte verschiebt. Usecase ist oft so, dass man erst mal in Ruhe auf der Karte das Zielgebiet aussucht, dann kann man auch gezielt reload drücken, um die Ladepunkte zuladen. Oft will man die Punkte in einem bestimmten Gebiet oder entlang einer geplanten Route suchen, das ist für mich primär der Use-Case dafür. Deswegen habe ich das so bewusst mit dem Knopf implementiert.
