### ISSUE TITLE
Tweak popover size in regular width environments (iPad)

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#19]
Das Info-Fenster für Ladepunkte ist beim iPhone bildschirmfüllend, beim iPad wird ein Fenster eingeblendet. Das Fenster hat etwa 2/3 der Bildschirmhöhe, man muss immer scrollen. Falls man die Höhe anders programmieren kann - wie würde es wirken, wenn das Fenster höher wäre?

**Comment by remuslazar** [comment]
@secuder auf dem iPad wollte ich durch das Fenster nicht die Karte zu sehr abdecken. Hat zumindest mal mit OCM gut gepasst. In der GE Datenbank hat man aber viel mehr Infos, ich werde auch mal selber testen und ggf. mit dem nächsten Update verbessern. Aktuell habe ich mich zu sehr auf die iPhone Version konzentriert, damit die GE Unterstützung raus gehen kann..

**Comment by remuslazar** [comment]
Internal note: resolved with https://github.com/remuslazar/EVPlugFinder/commit/71e0982fd1a15455aa4b4534b5ab9dcd2901f5bf
