### ISSUE TITLE
Filter - Darstellung der Ladepunkte - Markierungen

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#2]
1. Wenn das Filterfeld aufgerufen ist, kann man die Karte nicht verschieben oder Zoomen - das irritiert, weil die Karte bei Filteränderung selbstständig ein- oder auszoomt und man das nicht sofort "korrigieren" kann.

2. Es ist unklar, was ein Schnelllader ist - 11, 22, 43kW? 

3. Werden die Farben für die Nadeln irgendwo erklärt oder muss man da selbst drauf kommen?

4. 11kW Typ 2 Dosen haben die gleiche Farbe wie 3kW Schuko-Steckdosen - das sollte unterscheidbar sein, da der Unterschied zu signifikant ist: Bei 11kW braucht man 1-2 h bis man weiterkommt, das ist unterwegs brauchbar. Bei 3kW braucht man 4-6 h, das ist unterwegs nicht oder nur in Notfällen brauchbar.
 
5. Der eigene Standort wird mit dem Kreis markiert - wozu aber ist die Markierung in der Mitte des Bildschirms, die beim Scrollen auftaucht - kann man damit was machen oder ist die nur hübsch?

6. Ich habe eine weitere Markierung auf der Karte, die wie ein Standort aussieht: vier kleine Pfeile diagonal, in der Mitte eine Art Recyclingpfeil - was ist das?

**Comment by remuslazar** [comment]
@secuder danke fürs Feedback. Dazu kann ich folgendes erklären

1) ja, das ist technisch bedingt so, das Fenster ist als "Pop-Over" und man muss erst mal außerhalb klicken damit der Popover zu geht. Aber klar, verstehe die Problematik, ich werde hier schauen, was man tun kann, damit das Fenster auch beim scrollen automatisch zu geht. Ich denke, das wäre in diesem Kontext das richtige.

2) Ob Schnelllader liefert mir die API schon, siehe `ChargerTypes ` hier http://api.openchargemap.io/v2/referencedata/

3) siehe http://remuslazar.github.io/EVPlugFinder/, ich habe die Legende dort dokumentiert. Aber ja, ich werde vermutlich eine kurze "Hilfe" zu der App programmieren, welche man bei Bedarf ein und ausblenden kann. Dort kann ich das und auch den Hinweis auf die Settings unter bringen

4) Pin-Farbe oder Anschlussfarbe im Detail-Fenster? Falls letzteres gemeint ist, sehe ich das nicht so tragisch, aber klar, das könnte ich noch anders stylen. Falls ersteres, wie gesagt, die Info kommt von der API, ich nehme das 1:1 und mappe es nur entsprechend.

5) das ist der Kartenmittelpunkt, was bei einem Reload auch verwendet wird. Siehe auch 6)

6) jedes Mal, wenn man auf reload dückt, wird der Bereich um diesen Mittelpunkt neu geladen. Das ist nur ein Hinweis, dass man weiß, wo der Mittelpunkt war wenn man manuell die Karte verschiebt.

Ich hoffe, ich konnte ein wenig Klarheit schaffen. Zu 1) mache ich mir mal kurzfristig Gedanken, das kann ich sicher mit der nächsten Patch-Level-Release fixen.

**Comment by remuslazar** [comment]
@secuder ich habe soeben einige separate Issues erstelle für einige der genannten Punkten, alles andere konnte ich hoffentlich erläutern. Danke nochmals fürs Feedback!

Ich habe das alles auf Englisch verfasst, da es auch meine "Entwicklersprache" ist, außerdem möchte ich auch die Zielgruppe nicht auf den deutschsprachigen Raum unbedingt beschränken. Kommentare auf Deutsch sind auch ok, da bin ich pragmatisch und kann auch gut Deutsch, auch wenn das nicht meine Muttersprache ist;)

**Comment by secuder** [comment]
> _das ist der Kartenmittelpunkt, was bei einem Reload auch verwendet wird. Siehe auch 6)

jedes Mal, wenn man auf reload dückt, wird der Bereich um diesen Mittelpunkt neu geladen. Das ist nur ein Hinweis, dass man weiß, wo der Mittelpunkt war wenn man manuell die Karte verschiebt._

Hm, warum bleibt das beim Reload nicht der Mittelpunkt? Es gibt Fälle, da wandert dieser Punkt aus.

**Comment by remuslazar** [comment]
@secuder Der Punkt mit dem "Reload" Icon in der Mitte bedeutet, "hier hat man das letzte Reload gemacht. Mit anderen Worten: die Stationen, die gerade angezeigt werden, beziehen sich auf diesem Punkt". Wenn man die Karte manuell verschiebt, so verschiebt sich das auch mit, ist also nicht mehr Mittelpunkt der Karte. Erst wenn man erneut auf Reload drückt, so wird der aktuell gesetzte Kartenmittepunkt übernommen.

Ist wohl ein wenig schwer zu erklären, evtl. mache ich diese Funktionalität auch ganz anders, ich werde ein Paar Sachen ausprobieren, ob man das nicht noch simpler machen kann..

**Comment by secuder** [comment]
ich meine: ohne dass ich manuell verschiebe, einfach durch das Reload verschiebt sich der Mittelpunkt - ich glaube, um die Gesamtheit der gefundenen Ladepunkte in der Nähe bildfüllend unterzubringen. Wenn es im Westen mehr gibt als im Osten, dann verschiebt sich der Mittelpunkt. Insofern irritiert diese Markierung etwas.
Ich verstehe, dass sie Sinn macht, weiß aber nicht, ob sie nicht in gleichem Maße irritiert - ich bin gespannt, für was Du Dich letztlich entscheidest :-)

**Comment by secuder** [comment]
jetzt wo der Punkt fehlt, verstehe ich besser, wozu er gut war :-)
(vgl. #18 )

- no action required -
