### ISSUE TITLE
"Map-Origin" configurable (currently fixed to the user location)

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#20]
The charging points can be displayed in a well-arranged list.
But the order of this list is unclear: While the distance to the actual location seems to be correct, the list is not sortet according to the distance.
(Maybe it is sorted according to the center of the map when the Reload button was hit - this becomes questionable when the center of the map has been changed.)

**Comment by remuslazar** [comment]
no, the distance is _always_ calculated against the current user location. This makes sense in most circumstances, to get an estimate about how far the station is from the _current_ location.

The list is ordered by the distance to the map center (at the time as the reload was triggered). Doing that, the user has both estimates at a glance.

**Comment by secuder** [comment]
that's what I thought :-)
But there might be a reason to zoom in and to re-center the the map to a point of interest (e.g. the location one is about to load his car). So it would be good if the list would be ordered against the new center of the map.

**Comment by remuslazar** [comment]
@secuder yes, the "new center", let's call it "origin" should be somehow user-configurable/selectable. So then the above calculations (distance, re-centering etc. should then target this point. Somehow also related to #7

**Comment by remuslazar** [comment]
## Sneak-Preview: POI Search with Completion 
![bildschirmfoto 2016-12-16 um 12 30 06](https://cloud.githubusercontent.com/assets/6108134/21261493/16874fb2-c38c-11e6-8695-4d80f936f1c2.png)
