### ISSUE TITLE
"No Issue"

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#21]
Mit der GE-Datenbank funktioniert es genauso gut wie mit der OCM :-)

Erst heute habe ich gemerkt, dass man sich durch das Drücken des Fahrzeugsymbols zu der Ladestation navigieren lassen kann. Schön!

**Comment by remuslazar** [comment]
"No Issue" bedeutet auf jeden Fall weniger Arbeit für mich:) Danke für das Lob!
