### ISSUE TITLE
Öffungszeiten auf Englisch

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#22]
Öffnungszeiten werden im Info-Fenster auf Englisch angezeigt: 
[http://www.goingelectric.de/stromtankstellen/Deutschland/Schweinfurt/Freizeitbad-Silvana-An-den-unteren-Eichen-1/683/](url)

**Comment by remuslazar** [comment]
Wird bereits in https://github.com/remuslazar/EVPlugFinderPublic/issues/17 behandelt.
