### ISSUE TITLE
New Filter Option: "only open stations"

### ISSUE THREAD

**Issue by remuslazar** [remuslazar/EVPlugFinderPublic#28]
When set, this option should respect the "opening hours" info, if available, and filter out stations which are closed at the current time of the request.

**Comment by remuslazar** [comment]
Currently blocked, see http://www.goingelectric.de/forum/goingelectric-stromtankstellen/offizielle-api-t20221-20.html#p437257

**Comment by remuslazar** [comment]
Mockup

![bildschirmfoto 2016-12-14 um 13 33 29](https://cloud.githubusercontent.com/assets/6108134/21182166/fc5b584e-c201-11e6-8db3-12fe7c09f4fe.png)

**Comment by svebae** [comment]
Sind die Pins so vorgegeben oder kann man das individueller gestalten? Der Filter "Now open" würde ja die geschlossenen Ladesäulen ausblenden. Das ist gut so. Nur finde ich man sollte den Ladesäulen-Pins das optisch ansehen, ob sie geöffnet sind oder nicht. Auch ein kleine "24" an den Kopf des Pins für Rund-um-die-Uhr geöffnete Ladesäulen wäre nützlich.
Aber damit kann man sich erst befassen wenn die GE-API die Infos effizient liefert.

**Comment by remuslazar** [comment]
@svebae siehe http://www.goingelectric.de/forum/goingelectric-stromtankstellen/offizielle-api-t20221-20.html#p437257

Da habe ich just eben was geschrieben.

Genau, das ist eine gute Idee, mit der Farbe. z.B. Hellgrau bzw. mit einem Alpha (durchsichtig) versehen, wenn geschlossen. Dann hat man beides, die Unterscheidung ob Schnellladesäule oder normal, durch den Alpha zusätzlich die Info, ob aktuell geöffnet. Oder mit einem anderen Pin Icon versehen, da muss man einfach ein Paar Sachen empirisch ausprobieren.

Die Pins sind nicht vorgegeben, ich nutze allerdings die Default-Icons, die mir das MapKit Framework bietet. Kann man auch andere ausprobieren, ich finde jedoch diese Icons schön und auch nicht zu aufdringlich bzw. unruhig, auch nicht zu groß, dass die Karte dadurch zu arg verdeckt ist.
