### ISSUE TITLE
GE API: Workaround "barrierfree" API filter option

### ISSUE THREAD

**Issue by remuslazar** [remuslazar/EVPlugFinderPublic#30]
According to the GE API documentation, the `barrierfree=false` filter should filter out all charging points which are not available for public use (payment using EC/credit card etc.:

see http://www.goingelectric.de/stromtankstellen/api/dokumentation/
> nur Ladepunkte, die ohne Vertrag mit den üblichen Mittel - Bargeld, EC. o. Kreditkarte, beliebige RFID-Karte - nutzbar sind, boolescher Wert

Currently there are quite a few charging stations tagged as `barrierfree=false` being public accessible, like e.g.

http://www.goingelectric.de/stromtankstellen/Deutschland/Ludwigsburg/Aldi-Sued-Martin-Luther-Strasse-82/9187/

```
      "barrierfree": false,
```

To workaround this issue, a pragmatic approach will be to just ignore the above filter if the filter "only free charge"  also being selected.

**Comment by remuslazar** [comment]
See http://www.goingelectric.de/forum/goingelectric-stromtankstellen/ge-datenbank-ohne-vertrag-flag-oft-fehlerhaft-t20576.html

**Comment by secuder** [comment]
This is a pregmatic approach but you have to consider a certain mismatch rate for loading points where e.g. a specific RFID is mandatory  (no idea, how many these could be) - and the unusual effect that turning an additional filter ON results in more results than without it. 
I understood from the discussion at the GE-forum that they refrain from changing the Aldi loading points in a batch run. For whatever reason.
