### ISSUE TITLE
AC Schnellladung wird bei OCM nicht angezeigt

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#34]
### Filterfehler bei Verwendung der OCM Datenbank: AC Schnelllader werden nicht angezeigt. 
(Bei der GE Datenbank werden sie angezeigt)

**Einstellungen:**
AC Stecker gewählt
AC Schnelllader-Fahrzeug
AC Schnellladung >=20kW

![img_3354](https://cloud.githubusercontent.com/assets/24484266/21281925/db5f2c56-c3f0-11e6-910a-7e92bc672968.PNG)

**Ohne Filter:** 
AC Ladepunkt mit 22kW Leistung wird angezeigt

![img_3355](https://cloud.githubusercontent.com/assets/24484266/21281928/db86e8b8-c3f0-11e6-9a99-be6e32ca23e3.PNG)

**mit Filter _Nur Schnelllader_:**
AC Ladepunkt mit 22kW Leistung wird nicht mehr angezeigt

![img_3356](https://cloud.githubusercontent.com/assets/24484266/21281927/db86ca5e-c3f0-11e6-8b5c-16183f86bcbe.PNG)

**Comment by remuslazar** [comment]
@secuder ich schaue mal, vermutlich ist das mit der aktuellen API von OCM nicht lösbar. Dort kann man nur nach der Leistungsklasse filtern, level3 ist "Fast Charging", sind aber zahlreiche Einträge drin, die falsch klassifiziert sind.

Ich schaue mal, ob ich einen Workaround dafür finde, hat aber erst mal low prio..

**Comment by remuslazar** [comment]
@secuder good news: ich habe gerade die OCM API erneut angeschaut und offensichtlich gibt es (neu) eine Option "minpowerkw", die ich dann nutzen kann. Mit anderen Worten, ich kann die gleiche Logic wie bei GE auch bei OCM implementieren.

**Comment by secuder** [comment]
Sonst hättest du die Einstellungen in Abhängigkeit von der gewählten Datenbank programmieren können - aber mit der neuen Option wird es natürlich besser
