### ISSUE TITLE
Infofenster der Ladepunkte unterschiedlich breit (iPad)

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#36]
Die Infofenster der Ladepunkte sind in Abhängigkeit von der gewählten Datenbank unterschiedlich breit.

**Comment by remuslazar** [comment]
ja, das ist absichtlich so implementiert. Da in der GE Datenbank viel mehr Info vorhanden ist, macht es Sinn, die Popovers größer darzustellen. In OCM war die Größe wie sie war ok, dachte ich. Das kam nur dann auf, als man die GE Quelle implementiert hat, dort hat ja auch die Tabelle viel mehr Sections etc. Daher wird diese je nach Quelle unterschiedlich berechnet.
