### ISSUE TITLE
Info überdeckt durch Menue

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#39]
Ladepunktinformation ist durch das Menue überdeckt. Vielleicht lässt sich das anders lösen?
![img_3375](https://cloud.githubusercontent.com/assets/24484266/21295873/b352ab38-c55e-11e6-9b4e-26ff5639164f.PNG)

**Comment by remuslazar** [comment]
das könnte man ggf. mit einem Aufwand tun.. jedoch würde ich sagen, wenn die Info, die verdeckt ist, im konkreten Fall wichtig ist, einfach den Pin entsprechend verschieben, damit diese sichtbar wird.
