### ISSUE TITLE
Use a finer grained filter for charging level (power)

### ISSUE THREAD

**Issue by remuslazar** [remuslazar/EVPlugFinderPublic#4]
### Status Quo and Motivation

Currently there is only a binary switch on the filter pane "show only fast-charging". This filter should be finer-grained, so the user can also select e.g. available AC (16/32A) plugs but not "Schuko"

### Technical Details

The used API distinguishes between 3 distinct "charging level" classes:

```
"ChargerTypes": [
    {
      "Comments": "Under 2 kW, usually domestic socket types",
      "Title": "Level 1 : Low (Under 2kW)"
    },
    {
      "Comments": "Over 2 kW, usually non-domestic socket type",
      "Title": "Level 2 : Medium (Over 2kW)"
    },
    {
      "Comments": "40KW and Higher",
      "Title": "Level 3:  High (Over 40kW)"
    }
  ],
```

The API only allows queries using a `ChargerType`list, so the filter should reflect this classification, showing e.g. a slider with 3 steps for the "minimum level". And because the `ChargerType` value is also being used for the pin colors, the new filter should also use the same colors to make the UX more intuitive and consistent.

Note: in Germany, regular "Schuko" connections, despite of having more than 2kW are also tagged as "Level 1".

Relates to #1

**Comment by secuder** [comment]
even with settings set to "Schuko (Type F) OFF" the APP offers the loading point "Kulinario" in Schweinfurter Straße 7, 97525 Schwebheim, Germany.
Data base shows 2x 3kW Schuko and 0x several other plugs for this location, so this might be a problem with the database - maybe you are able to sort them out anyway.

**Comment by remuslazar** [comment]
@secuder the "0x" is definitely a bug in the OCM data, yes, the "count" property being optional it should have been `null` in the JSON having the semantic "number of connections unknown". Unfortunately the "0" means the same for the OCM logic, for that reason the filtered query also lists this entries.

**Comment by secuder** [comment]
understood - it will be hard to improve the database at this point :-) but any possibility to filter that in the APP?
Not good, I know, but better than false readings

**Comment by remuslazar** [comment]
@secuder I can't workaround this issue, this has to be done in the OCM database layer.. I will try to open a bug request there..

**Comment by remuslazar** [comment]
workaround implemented in Build 10

**Comment by secuder** [comment]
Hm, workaround does not work on build 12: Loading point "Kulinario" in Schweinfurter Straße 7, 97525 Schwebheim, Germany is still on display even with _Schuko OFF_.
(Data base shows 2x 3kW Schuko and 0x several other plugs for this location)

**Comment by remuslazar** [comment]
@secuder this is an issue with the OCM database. 0x means there often "we simply don't know how many plugs are available". So I can't just filter them out, this will be just wrong. It would have been better to save a `null` instead of the int `0`, but ..

**Comment by secuder** [comment]
I see, but what kind of workaround have you implemented then?

**Comment by remuslazar** [comment]
my comment is just wrong, I will delete it
