### ISSUE TITLE
Typ 2 icon

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#40]
Nette neue Icons. Beim Typ 2 Icon fehlt die typische Abflachung und deshalb sieht das eher nach CEE aus (dabei hat CEE ein sehr schönes eigenes Icon).

Eigentlich müsste das Icon doch eher wie CSS ohne die beiden unteren Kontakte (und dafür etwas größer) aussehen...?!?
![img_3377](https://cloud.githubusercontent.com/assets/24484266/21295904/594050f4-c55f-11e6-8392-84f2c99581f2.PNG)

**Comment by remuslazar** [comment]
alles klar, ich gebe die Info weiter. Die Icons sind noch nicht final, da wird man noch daran feilen.

**Comment by secuder** [comment]
(Das ist sowieso Jammern auf hohem Niveau 😇)

**Comment by remuslazar** [comment]
@secuder nee, das ist ok, ich bin auch sehr Detail-verliebt. Icons werden sicher noch überarbeitet, da muss man noch einige Iterationen machen, bis das passt! Dabei ist es jetzt auch aufgefallen, dass bei dem Typ2 Anzahl Pins usw. nicht stimmen. Wird man ggf. abstrakter machen, in der Größe wirken diese Details eher unruhig.

**Comment by secuder** [comment]
Das neue Icon passt zwar von den PINs her, aber nicht von der Form des Steckers, siehe Bild
![mennekes-stecker-typ2_334](https://cloud.githubusercontent.com/assets/24484266/22469538/a2b735ec-e7cc-11e6-9280-0a312247cf5d.jpg)
