### ISSUE TITLE
Zoom-Automatik nach "reload" und POI Suche

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#41]
Für den Zoom fehlt noch eine praktikable Automatik. Auf dem Land, bei geringer Ladesäulendichte, ergibt sich ein stimmiger Zoom. Wird dann nach Schnellladern gefiltert, wird sehr weit herausgezoomt, so dass man einen viel größeren Kartenausschnitt und auch mehr (!) Ladesäulen sieht als ohne den Filter. 

Bei Adressensuche (cooles Feature! 🙂) in einer Stadt passt der Zoom nicht: Hier interessieren ja die Ergebisse in näherer Umgebung des Ziels - liegt die Adresse zufällig in Berlin, so wird aber so weit rausgezoomt, dass man plötzlich die ganze Stadt auf der Karte hat und von den Ladesäulen gänzlich erschlagen wird.

**Comment by remuslazar** [comment]
Zoom arbeitet momentan so, dass die Karte um den gewählten Punkt zentriert bleibt, wird so gezoomt dass _alle_ Ladestationen sichtbar sind und auch mit einem kleinen Padding an den Rändern (15%). Sonst war das oft so, dass die Stationen sehr nah an den Ränder platziert wurden, das hat optisch nicht so schön ausgesehen. 15% habe ich empirisch ermittelt, so dass das auf iPhone/iPad ok aussieht.

Wenn man nur Schnellladestationen will, so wird die Suche mit einem größerem Radius gemacht, das finde ich sinnvoll, weil man dann meist größere Distanzen überbrücken will, da will man einen größeren Radius haben. Zoom arbeitet dann genauso, heißt nun, wird mehr heraus gezoomt, weil auch potentiell mehr Ladestationen gibt.

Wie soll denn eine praktikable Automatik sonst aussehen? Wenn du einen konkreten Vorschlag hast, so kann ich das gerne damit experimentieren. Ich habe auch einiges hin-und-her probiert und bin mit der o.g. Lösung am glücklichsten geworden. Im Prinzip wie früher (bis Build 10), jedoch mit dem Unterschied, dass Mittelpunkt stehen bleibt.

Ach ja, noch was: wenn man mit dem Finger auf der karte auf einen beliebigen Punkt "long press" macht, so werden die Stationen um diesen Punkt geladen und _ohne_ dass die Karte neu zentriert oder gezoomt wird.

Filter "ohne Anmeldung" ist immer sinnvoll IMHO, sonst wird man fast überall von den vielen unnützen Ladestationen erschlagen, z.B. in Stuttgart von den EnBW Stationen, wo man ziemlich sicher nicht laden will (wenn man nicht _muss_,..)

**Comment by remuslazar** [comment]
@secuder hast du hier noch Anmerkungen dazu bzw. Vorschlag, wie man das noch anders/besser machen könnte? Sonst würde ich das zu machen, ich finde die aktuelle Lösung ausreichend praktikabel aus Usability-Sicht.

**Comment by secuder** [comment]
Ja, ich denke mir noch was aus, kann aber das dann auch neu eröffnen. Diese Woche bin ich ziemlich unter Wasser...

**Comment by secuder** [comment]
Der Filter "ohne Anmeldung" ist eigentlich ein eigenes Thema. Der Filter ist natürlich sinnvoll, dennoch würde ich ihn beim allerersten Start der APP nicht als default setzen, weil das der USER-Erwartung für Filter widerspricht. Ein Filter reduziert ein erwartetes Ergebnis. Deshalb sollte zunächst immer alles angezeigt werden, was man nicht durch die Wahl der Einstellungen (Stecker etc.)  herausgenommen hat. Danach kann man als USER mit den Filtern experimentieren, um zu den gewünschten Ergebnisse zu kommen.

**Comment by secuder** [comment]
Zum Thema Zoom: Das bei _Schnelllader_ weiter rausgezoomt wird, verstehe ich und finde ich nachvollziehbar.
Bei der Suche nach **Kontakten** ist der Zoom unabhängig vom Filter _Schnelllader_ deutlich zu weit. Ich interessiere mich ausdrücklich für Ladestationen nahe der Kontaktadresse, denn ich will da wahrscheinlich jemanden besuchen und dann nicht ewig weit laufen. Andererseits sollen ein paar Ladestationen sichtbar sein.
Ich fände es ideal, wenn der Zoom bei der Suche so gewählt wäre dass der Maßstab (die Linie oben links) 1km Länge hat.
Für ein kleines Display wäre die Grenze zu 1,5km gut, für große die Grenze zu 750m (oder halt für alle Displaygrößen die Mitte davon...).
Idealerweise müsste die APP jetzt prüfen, ob mindestens zwei Ladestationen im Kartenausschnitt sichtbar sind. Falls nein, zoomt die APP so lange raus, bis mindestens zwei Ladestationen auf der Kartenausschnitt sichtbar sind.

Könnte man sowas mit vertretbarem Aufwand realisieren?

**Comment by helmutnn** [comment]
Das aktuelle Zoom-Verhalten entspricht nicht meinen Erwartungen. Besonders wenn ich (mühsam) in einen bestimmten Bereich der Karte gezoomt habe und Reload antippe oder eine der Einstellmöglichkeiten ändere möchte ich den Bereich nicht verlieren. Den Reload per Force Touch auszulösen ist kein guter Ersatz, der Benutzer sollte den Bereich in der Ladestationen angezeigt bekommen möchte vorgeben und ohne weiteres halten können. Wenn er wieder einen größeren Bereich sehen möchte, dann kann er einfach herauszoomen.

**Comment by remuslazar** [comment]
Das ist nicht force touch sondern "long press".

Nun zu dem Zoom Verhalten: bei long press wird der Ausschnitt beibehalten, sonst wird es mittig gelassen aber so weit heraus gezoomt, dass alle Treffer auf der Karte angezeigt werden können. Da die Karte kein automatischen Nachladen triggert, wenn diese bewegt oder gezoomt wird, so ist das auch für den User IMO wichtig zu erkennen, welche Treffer bei der Suche resultiert haben, das möchte der User lieber visuell erfassen. Danach kann der User beliebig zoomen und sich mit dem long press neue Ladestationen um den Punkt laden lassen, je nach Gusto.

Fetch Request berücksichtigt übrigens auch nicht den Kartenausschnitt, was angezeigt wird, lediglich Mittelpunkt wird dabei verwendet. Radius für die Suche (GE) bzw. Limit (OCM) ist fest und kann in den Settings eingestellt werden. Das variiert auch wenn man "nur Schnelllader" filtert, weil das eher dem Use-Case entspricht, das habe ich auch weiter oben in diesem Thread elaboriert.

Vielleicht einfach erst mal die App draußen im "Feld" ein Paar Tage verwenden, diese Tweaks sind auch dadurch entstanden, weil ich unterwegs mit der App die Erfahrungen gemacht habe (+User Feedback natürlich). Wenn man nur so erst mal damit "rum spielt" entspricht das ggf. nicht dem Use-Case, was die App abdecken möchte. Klar, die App sollte auch Spaß machen, keine Frage, aber in erster Linie eine Funktion erfüllen ;)

**Comment by remuslazar** [comment]
.. damit das nicht unter geht, @secuder 

> Ich fände es ideal, wenn der Zoom bei der Suche so gewählt wäre dass der Maßstab (die Linie oben links) 1km Länge hat.
> Für ein kleines Display wäre die Grenze zu 1,5km gut, für große die Grenze zu 750m (oder halt für alle Displaygrößen die Mitte davon...).

Das ist ein interessanter Ansatz, den ich hier gerne weiter verfolgen werde.

**Comment by helmutnn** [comment]
Es geht um die Usability (hier Destination Charging) und eingeübtes Verhalten (Aktivieren/Deaktivierung von Layern oder Ändern von Filtern): Ich suche einen (kleinen) Bereich um meine Zieladresse aus in dem ich eine Ladestation brauche. Wenn mir keine Station mit meinen Wunschkriterien (z.B. kostenlos) angezeigt wird dann ändere ich die Filterkriterien. Wenn es dann immer noch nichts gibt erweitere ich den Bereich sukzessive um zu schauen, ob die nächsten Stationen in der Nähe vom Fussweg noch akzeptabel und auch sonst für mich brauchbar sind (z.B. ob ich die Ladekarte habe oder wie das Ladelog dazu aussieht). Als Anwender brauche ich dann stets einen stabilen Bereich bei Änderung der Suchkriterien oder bei der Aktualisierung der Ladesäulen. Es wäre toll, wenn es zumindest optional möglich wäre diese Stabilität des Ausschnitts in der Ladestationen App zu erreichen.

**Comment by remuslazar** [comment]
@helmutnn 👍  guter Punkt, ja. _Wenn man den Filter ändert, wie beschrieben, geht der Kontext u.U. verloren durch das zooming_. Ich werde ein Paar Optionen empirisch mal ausprobieren und schauen, was man hier noch tunen könnte! Danke!
