### ISSUE TITLE
Routing App Chooser

### ISSUE THREAD

**Issue by remuslazar** [remuslazar/EVPlugFinderPublic#43]

**Comment by remuslazar** [comment]
Already implemented: Handoff and Activity Continuation:

![img_0649](https://cloud.githubusercontent.com/assets/6108134/21389456/23360c9a-c782-11e6-82b3-6bc5d82cfb38.PNG)

**Comment by fschulze** [comment]
In the meantime it would be nice if one could easily copy the address for use in other apps.

**Comment by remuslazar** [comment]
@fschulze this is actually quite easy: just use the standard OS features:

![bildschirmfoto 2017-08-17 um 20 58 02](https://user-images.githubusercontent.com/6108134/29428804-cc68ee4a-838e-11e7-870e-60c72d532f1d.png)
