### ISSUE TITLE
APP Einstellungen - Hinweistext

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#44]
Am Hinweistext könnte ein bisschen gefeilt werden.
Er lautet:
_Die verfügbaren App-Einstellungen wurden erweitert. Möchtest Du diese App jetzt konfigurieren? (empfohlen)_
Bei einer Erstinstallation wurde ja genaugenommen nichts erweitert.
Vorschläge:
Ganz einfach:
_Möchtest Du diese App jetzt konfigurieren? (empfohlen)_
Oder:
_Diese App bietet erweiterte Einstellungen. Möchtest Du diese App jetzt konfigurieren? (empfohlen)_
(--> Die Einstellungen wurden nicht erweitert, sondern sind gegenüber anderen Einstellungen erweitert bzw umfangreicher)

**Comment by remuslazar** [comment]
ja, danke, ich bin auch kein "native German speaker". Ich denke, ich werde die Unterscheidung machen, ob die App neu installiert wurde oder auf eine neue Version upgegraded und dann verschiedenes anzeigen. Dann ist das eindeutiger

**Comment by secuder** [comment]
(das ist auch sehr kleinkariert von mir...) :-)

**Comment by helmutnn** [comment]
Ich wusste bei der Erstinstallation auch nicht, was ich hier genau machen sollte. Ich wurde dann auf die Einstellungen des iPhones geleitet und hatte damit den Kontext zur App verloren. Da ich diese Möglichkeit der Konfiguration schon kannte habe ich (ganz weit) nach unten gescrolled und zunächst unter EV* gesucht (den Namen des Projekts hier :). Dann also nochmal raus aus den Einstellungen und den Namen der App nachgesehen und wieder zurück in die Einstellungen und fündig geworden.

Ich würde die Einstellungen in jedem Fall in der App anbieten, damit der Benutzer das im Kontext schnell ändern kann und nicht genötigt wird für Änderungen raus- und wieder reinzugehen.

**Comment by remuslazar** [comment]
@helmutnn aber eigentlich sollte der Klick genau zu den App Einstellungen leiten und dann auch links oben zurück zu der App. Ich hänge mal 2 Screenshots rein, wir es hier aussieht (Simulator).

Das ist also the expected behavior.. im Code mache ich auch nichts wildes, wie man die Settings für die App abruft ist auch ausreichend dokumentiert und da nutze ich auch die public API dafür..

![bildschirmfoto 2016-12-23 um 14 01 19](https://cloud.githubusercontent.com/assets/6108134/21454401/717bdcd0-c918-11e6-8fc4-e7c8c222538f.png)
![bildschirmfoto 2016-12-23 um 14 01 52](https://cloud.githubusercontent.com/assets/6108134/21454400/717b9130-c918-11e6-8de8-37795a544809.png)
![bildschirmfoto 2016-12-23 um 14 02 06](https://cloud.githubusercontent.com/assets/6108134/21454399/715ad3e6-c918-11e6-9b58-c11c74d83156.png)

**Comment by helmutnn** [comment]
Das hat auf dem iPhone 7 Plus mit iOS 10.2 so nicht funktioniert, er hat mich ganz nach oben in den Einstellungen navigiert.

**Comment by remuslazar** [comment]
@helmutnn danke, den Fall hatte ich nie. Ab und zu crashed die Settings App, das hatte ich in einem anderen Kontext auch, evtl. ist das passiert? Das wäre dann etwas, was die App weder abfangen noch beeinflußen kann.. Kannst du mal testen, wenn du die App einfach mal deinstalliert und dann neu installierst, ob es dann klappt mit dem Link?

**Comment by remuslazar** [comment]
und.. die Settings werde ich nicht in die App verlagern, die Diskussion gab es einige Male. Die Settings sollten etwas sein, was man einmalig macht bzw. selten, wenn man z.B. ein neues Auto gekauft hat. Alles, was man zur Laufzeit machen muss sollte mit dem Filter abgedeckt sein. So die Philosophie.

**Comment by helmutnn** [comment]
Es kostet ja nichts ein Zahnrädchen anzubieten und den Schirm in der App aufzumachen. Das würde ich nicht zu dogmatisch sehen. Ich konnte als Benutzer die Unterscheidung zwischen internen und externen Einstellungen nie richtig nachvollziehen und möchte immer direkt im Kontext der App darauf zugreifen können. Die Einstellungen des iPhones sind so weit weg und diese Liste ist bei manchem sehr lang. Es gibt auch Benutzer, die mehr als ein E-Auto im Zugriff haben oder einfach mal ein bisschen damit herumspielen möchten. Gerade wenn man diese Einstellungen sehr selten ändert erinnert man sich im Fall des Falles eher nicht daran, wo sie zu finden sind.

**Comment by remuslazar** [comment]
@helmutnn 
das sehe ich anders, die Settings sind ein wichtiger Bestandteil des Apple Ökosystems und das möchte ich auch maximal unterstützen. Das die Leute nicht so damit umgehen liegt eher daran, dass die Apps halt, gelinde gesagt, "suboptimal" designed sind.

Die Apple Apps nutzen die Settings wo es Sinn macht, da kommen die Leute offensichtlich auch damit klar.

Ich höre ja auch auf die Notifications, wenn sich die Settings geändert haben und reagiere entsprechend. Wenn man also damit "herumspielen" will, ist das nicht mehr als ein double klick auf die Home Taste, Switch to Settings and back. Das sehe ich nicht primär als Hindernis.

Mehrere Autos wäre etwas, was man mit Profile unterstützen könnte. Ich behaupte mal, das sind aber nur sehr wenige User, die davon profitieren würden, daher hat das erst mal low priority. Das bedeutet nicht nur Implementierungs/Test Aufwand sondern würde die App auch unnötig verkomplizieren für die, die nur ein Auto haben, was ich nicht möchte.

Ich hoffe, ich konnte dadurch ein wenig die Philosophie dahinter erläutern.

Wie ich schon sagte: wenn es noch andere Use-Cases gibt, die aktuell mit dem Filter so nicht abgedeckt sind, bin ich gerne bereit, mir darüber Gedanken zu machen und lasse mich auch auf Diskussionen ein. Aber die Settings generell über die App abrufbar zu machen wird nicht kommen. Das macht auch keine einzige App von Apple (z.B. die Kamera App). Da gibt es auch kontroverse Diskussionen darüber, hier bin ich halt bei Apple:)

**Comment by helmutnn** [comment]
Ich würde es den Benutzern nicht unnötig schwer machen. Die Einstellungen auch in der App anzuzeigen wäre ja kein Beinbruch. Ich würde immer vermeiden die Anwender zu erziehen, das bringt nur Frust auf beiden Seiten.

**Comment by remuslazar** [comment]
ja, das bin ich voll bei dir. Deswegen sind mir solche Details wichtig. Die Settings in die App zu verlagern wäre wie eine Kapitulation, man lässt es einfach zu, dass die Benutzer mit den Settings spielen, um etwas zu erreichen, was so nicht dafür richtig bedacht wurde. Dann lieber sich die Use-Cases genau ansehen und dann entsprechende Möglichkeiten in die App einbauen (in diesem Kontext z.B. mit einem finer-grained Filter, da gibt es schon ein Issue dafür).

**Comment by helmutnn** [comment]
Bitte nicht zu dogmatisch sein und die Usability im Auge halten...

**Comment by remuslazar** [comment]
darum geht's, genau:) Ich möchte lieber verstehen, welche Use-Cases es gibt und mir darüber Gedanken machen, gerade im Bezug auf UX. Daher bin ich sehr an das "WAS" interessiert, was die Benutzer tun (wollen) und nicht so sehr an das "WIE". Das "wie" will ich schon selber als Product Owner beantworten, von den Benutzern erwarte ich eher so eine Art "User Story", z.B.

> mein Use Case ist so und so, ich muss immer wieder dies und jenes finden und dafür muss ich aktuell diese Schritte unternehmen. Ich wünsche mir, dass es einfacher geht, um Zeit zu sparen

Dann kann das darunter liegende Problem besser verstehen und eine adequate Lösung implementieren. PS ich mache das nicht erst seit gestern:)

**Comment by helmutnn** [comment]
Mach es nicht zu kompliziert mit den Einstellungen, da braucht es keine komplexe und zeitraubende Use Case Analyse. Es ist gute und bewährte Praxis das in der App anzubieten.

**Comment by helmutnn** [comment]
Oder anders formuliert: Als Benutzer der Ladestationen App möchte ich alle Einstellungen innerhalb der App sehen und ändern können, um alle möglichen und eingestellten Optionen stets im Kontext derselben sehen und die App dazu nicht verlassen zu müssen.
