### ISSUE TITLE
Haptische Rückmeldung

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#45]
Ein langes Drücken auf den Bildschirm initiiert ein Reload.

Manchmal dauert das ein bisschen (abhängig vom Netz?).

Kann das Handy eine haptische Rückmeldung geben, zB einen ganz kurzen Vibrier-Impuls (wie beim 3D-Drücken)?

(gerne in den Einstellungen abstellbar... :-) )

**Comment by remuslazar** [comment]
@secuder ja, das ist schon so, braucht man halt iPhone 7/Plus

**Comment by secuder** [comment]
hm, müsste das nicht schon mit 6/Plus gehen? (geht bei meinem jedenfalls bei 3DDrücken - aber nicht in der App)
