### ISSUE TITLE
missing icon

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#46]
in OCM database following loading point shows an "?" instead of the type 2 icon:
OCM-67761: elektro Bühler GmbH

(maybe bug in database or missing icon for 43kW type 2?)

**Comment by remuslazar** [comment]
not all icons are currently implemented, the "?" icon is used as a fallback, if no specific icon being available.

**Comment by secuder** [comment]
in this case the normal type 2 icon would fit perfectly

**Comment by remuslazar** [comment]
duplicate https://github.com/remuslazar/EVPlugFinderPublic/issues/40
