### ISSUE TITLE
Ladebildschirm - Credits

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#47]
Im Ladebildschirm werden den Datenbanken "Credits" gegeben - die Anzeigedauer ist beim iPhone 5 okay, beim 6 Plus jedoch sehr kurz - das ist schön, weil es dann schnell losgeht mit dem Suchen, aber schade, wenn man Credits geben will. Auch bei meinem iPad lädt es sehr schnell.

(Das Icon für die APP finde ich übrigens sehr gelungen; der Ladebildschirm ist für die OCM Datenbank angemessen grün, aber mir fehlt das Blau von Goingelectric im Bild)

**Comment by remuslazar** [comment]
Ladebildschirm (Launchscreen) wird nur solange angezeigt, bis die App "ready" ist. Das geht normalerweise schnell. Wenn das Gerät erst mal Ressourcen frei machen muss (z.B. andere Apps schließen etc.), so kann das einen Moment dauern.

Wenn die App läuft, zeigt State Restoration normalerweise den LaunchScreen gar nicht mehr an, da werden Screenshots vom letzten Stand der App, wo sie noch lief, angezeigt und die App wird gestartet und mit State Restoration genau in dem Zustand versetzt, bevor sie geschlossen wurde (z.B. iPhone Reboot, Memory Pressure etc.). State Restoration habe ich mit Build 11 glaube ich erst implementiert, davor wurde der LaunchScreen des öfteren angezeigt, das sollte nich mehr so oft kommen.

Ich persönlich halte nicht viel von diese "Credits" Einblendungen, die App sollte ja in 1. Linie eine Funktion erfüllen. Der User weiß ja, woher die Daten kommen, auch führen die Links zu dem entsprechenden Portal, das reicht ja aus, muss man nicht bei jedem Start noch die User damit "behelligen".

Icon ist natürlich wichtig, dass das passt, damit sollte man die App möglichst präzise und schnell wieder erkennen, das erfüllt eine wichtige Funktion;)
