### ISSUE TITLE
Geokodierung Fehler -  Fehlermeldung bei fehlerhafter Adresse aus Kontakten

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#48]
_Geokodierung Fehler_
_Adresse "xxx" konnte nicht lokalisiert werden (Der Vorgang konnte nicht abgeschlossen werden. (kCLErrorDomain-Fehler 8.))._

Da war zugegeben ein Tippfehler in der Adresse, aber die Fehlermeldung ist sehr kryptisch. Kann man das abfangen und einen verständlichen Text ausgeben?

**Comment by remuslazar** [comment]
@secuder das wird schon abgefangen, die Fehlermeldung generiere ich ja auch selber (kommt nicht von iOS). Den 1. Part der Fehlermeldung ist meine Meldung, den 2. Part, in Klammern ist die lokalisierte Fehlermeldung vom Framework. Ich werde das so lassen, weil es sinnvoll ist, dass man mitbekommen, woran der Fehler lag. z.B. ob Adresse falsch oder ob kein Netzwerk verfügbar oder sonst was. Dass da noch die Codes mit kommen, ist halt so, so kann der User wenigstens mit dem Code googeln, wenn er noch mehr Infos dazu haben will.

Im code sieht das in Etwa so aus

```
        let alert = UIAlertController(
            title: NSLocalizedString("Geocoding Error", comment: "Alert Title Geocoding Error"),
            message: String.localizedStringWithFormat(
                NSLocalizedString("Could not geocode address \"%@\" (%@)",
                                  comment: "Geocoding Error Message Format String"),
                addressString, error.localizedDescription),
            preferredStyle: .alert
        )
```

Man könnte natürlich alle Error-Codes, die zurückkommen selber parsen und eine passende Fehlermeldung erzeugen, da da lohnt der Aufwand in diesem Falle nicht. Auch die Wartung später nicht, wenn in iOS11 da neue Codes dazu kommen etc.. Da ist `localizedDescription` quasi "wartungsfrei".

**Comment by secuder** [comment]
Oki. Ich fand das einfach komisch mit den zwei Klammern und dem Punkt nach der 8

**Comment by remuslazar** [comment]
ja, die () außen kommt von meinem Format String, das könnte man weglassen, stimmt! Ich ändere das mal!
