### ISSUE TITLE
AC Schnelllader Einstellung OCM

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#49]
Bei der AC Schnelllader Einstellung bei Verwendung von OCM ist irgendwas faul, was insbesondere auffällt, wenn 43kW AC Ladepunkte, die keine anderen Stecker oder Leistungen anbieten, betrachtet werden.
_Ich verstehe die Einstellung so, dass gelten soll (kursiv)_

_1. Type 2 Stecker ON - AC Schnelllader ON - Schnellladeleistung >=22kW - Filter Schnelllader ON --> Typ 2 Ladepunkte mit 22kW oder mehr werden angezeigt._ 
Angezeigt werden Type 2 22kW aber komischerweise **nicht** reine 43kW (zB Ladepunkt OCM-67761 in Schweinfurt oder Ladepunkt OCM-48751 in Drakenburg). Ladepunkte, die neben 43kW AC noch über andere Schnellladestecker (DC) verfügen, **werden** angezeigt. Es werden **keine** Schnelllader angezeigt, die gar kein Typ 2 Stecker haben wie zB OCM-45012

_2. Type 2 Stecker ON - AC Schnelllader ON - Schnellladeleistung >=22kW - Filter Schnelllader OFF --> **Alle** Typ 2 Ladepunkte werden angezeigt._ 
Angezeigt werden Type 2 11kW und 22kW, aber komischerweise **nicht** reine 43kW (zB Ladepunkt OCM-67761 in Schweinfurt oder Ladepunkt OCM-48751 in Drakenburg). Ladepunkte, die neben 43kW AC noch über andere Schnellladestecker (DC) verfügen, **werden** angezeigt. Es werden **keine** Schnelllader angezeigt, die gar kein Typ 2 Stecker haben wie zB OCM-45012

_3. Type 2 Stecker ON - AC Schnelllader OFF - Schnellladeleistung >=22kW - Filter Schnelllader ON --> tja, was soll hier angezeigt werden? Nur DC-Ladepunkte >=20kW?_ Falls ja, dann funktioniert das jedenfalls nicht, es werden angezeigt: Type 2 22kW **und** Typ 2 43kW (die reinen 43kW AC Ladepunkte werden überhaupt nur mit diesen Einstellungen angezeigt!, obwohl AC Schnelllader OFF eingestellt ist). Ladepunkte, die neben 43kW AC noch über andere Schnellladestecker (DC) verfügen, werden angezeigt. Es werden auch Schnelllader angezeigt, die gar kein Typ 2 Stecker haben (obwohl andere Stecker in den Einstellungen überhaupt nicht ausgewählt sind), zB OCM-45012 mit 20(!)kW CHAdeMo und CCS

_4. Type 2 Stecker ON - AC Schnelllader OFF - Schnellladeleistung >=22kW - Filter Schnelllader OFF --> **Alle** Typ 2 Ladepunkte werden angezeigt._ 
Angezeigt werden: Type 2 11kW, 22kW aber komischerweise **nicht** reine 43kW (zB Ladepunkt OCM-67761 in Schweinfurt oder Ladepunkt OCM-48751 in Drakenburg). Ladepunkte, die neben 43kW AC noch über andere Schnellladestecker (DC) verfügen, werden angezeigt, zB OCM-41020

Interessant verhält sich auch OCM-47761 (Type 2 11kW und 43kW+CEE 11kW und 3kW): 1 nein, 2 ja, 3 ja, 4 ja

Ich habe da einen ziemlichen Knoten im Kopf, wie das implementiert ist scheint mir das absolut nicht logisch. Die _AC Schnelllader_ Einstellung macht nicht, was ich als USER erwarte bzw. ich weiss gar nicht so recht, was ich erwarten kann.
Typ2 43kW Ladepunkte sollten immer angezeigt werden, wenn Typ 2 Stecker in den Einstellungen ausgewählt sind, egal ob _AC Schnelllader_ ON oder OFF. Ein 20kW DC Ladepunkt sollte ich nicht sehen, wenn _Schnellladeleistung_ >=20kW eingestellt ist. Ein DC Ladepunkt sollte nicht angezeigt werden, wenn nur Typ 2 Stecker eingestellt sind.

(Für die Goingelectric Datenbank habe ich mir das jetzt noch nicht angesehen)

**Comment by remuslazar** [comment]
@secuder also die Implementierung ist bei GE und OCM so:

1) es werden immer nur die Steckertypen gefiltert, welche auch in den Settings hinterlegt sind. Heißt also, da kommen nur Ladestationen, wo _mindestens_ eins von den Typen vorhanden ist.

2) wenn man "Fastcharging" Filter Option aktiv ist, dann wird folgendes gemacht:
   - Wenn die "AC Fastcharging" Option aktiv ist, so werden _zusätzlich_ Stationen gefiltert, wo die maximale Leistung über die eingestellte Schwelle ist (20 oder 43kW in den Settings)
   - Wenn die o.g. Option _nicht_ aktiv ist, so werden zusätzlich _nur_ die Steckertypen gefiltert, welche vom Typ _DC Fastcharging_ getagged sind (aktuell nur Tesla, CCS und Chademo)

Code hier:

```
        var connectionTypeIDs = PlugFinderUserDefaults.OCMSelectedConnectionTypes

        if filter.onlyFastCharge {
            params["minpowerkw"] = Int(PlugFinderUserDefaults.fastChargingMinPowerKW)
            if !PlugFinderUserDefaults.acFastChargingCapable {
                connectionTypeIDs = connectionTypeIDs.filter { dcPlugTypes.contains($0) }
            }
        }
```

Wie du siehst, ist da kein Rocket Science, was gemacht wird. Das macht genau das, was ich oben beschrieben habe (bzw. sollte es das tun ;)

Wenn da nicht das gewünschte raus kommt, so muss man den Fehler bei OCM ggf. suchen.

Auch kann man mit der OCM API selber experimentieren, man braucht nur einen Browser dafür:

https://openchargemap.org/site/develop/api

Ich werde vermutlich keine Zeit finden, um mich damit intensiver zu befassen, bin aber gerne bereit, einen anderen Algorithmus zu implementieren, wenn man hier andere Vorschläge hat, die nachweislich besser sind.

Lasse das also noch offen, hat aber (bei mir) erst mal nicht höchste Priorität.. Ich selber nutze nur GE zur Zeit und dort konnte ich keine Anomalien feststellen

**Comment by secuder** [comment]
Was heißt denn _zusätzlich gefiltert_? Durch einen Filter können es per Definition des Filters nur weniger Treffer werden.

**Comment by remuslazar** [comment]
genau das meinte ich doch damit, da wird zusätzlich ein weiteres Filter-Kriterium angewandt. Das ist alles mit logisch UND verknüpft. "Filter A" UND "Filter B" eben. Ist das nicht verständlich? Ich kann es nur noch auf Englisch probieren:)

**Comment by secuder** [comment]
Die genannten 43kW AC Stationen werden nur im Szenario 2. oben gefunden. Das ist kein sinnvolles, vom User erwartetes Ergebnis. Die müssen, weil Typ 2 Stecker, in **jedem** der Szenarios gefunden werden, sonst stimmt da was nicht. 

Auch nicht erwartet werden kann, dass im Szenario 3. Ladepunkte **unter** 22kW (Schnellladung ist in den Einstellungen als >=22kW definiert), die noch dazu DC Stecker sind (die ja nicht ausgewählt sind), angezeigt werden.

**Comment by remuslazar** [comment]
@secuder aber klar, im 1) wird nur nach kompatiblen Steckertypen gefiltert, da spielen die AC und Fastcharging Optionen doch gar keine Rolle... Wenn der User in den Settings Typ 2 ausgewählt hat, so werden die Stationen auch angezeigt. Die Logik habe ich doch versucht zu beschreiben, wenn das noch nicht verständlich ist, sorry:)

**Comment by secuder** [comment]
In meinen Augen gehst du bei den USE-CASES von der _DC + langsam-AC_ Voraussetzung im Hinterkopf aus, die sich aber in der Beschreibung der Einstellungen und Filter sich nicht wiederfindet und damit für AC Fahrer falsche Ergebnisse (siehe oben) bringt. 

OCM hat offenbar keine Priorität, aber das beschriebe Verhalten ist nachhaltig falsch. 

Ich erarbeite gern einen Vorschlag (oder zumindest mit), aber das hat für mich nur Sinn, wenn du meiner Argumentation folgen magst. womöglich ist es auch nicht mit einer Umbenennung der Einstellungen getan.

**Comment by secuder** [comment]
(Verstehe ich nicht, warum ein 43kW AC Typ 2 in Szenario 1. nicht angezeigt wird - Allrad Voraussetzungen sind doch erfüllt?)
(Gern auch auf Englisch)

**Comment by remuslazar** [comment]
@secuder also nochmals, damit wir die Sache abschließen können:

wenn die ACFastCharging Einstellung AKTIV ist (Zoe Fahrer), so wird im Prinzip nur nach Stationen, wo die Leistung über die eingestellte schwelle ist, gefiltert, wenn Fastcharging an ist.

Aus dem o.g. Code geht ja das hervor. `if !PlugFinderUserDefaults.acFastChargingCapable {`, also IF NOT, nur wenn NICHT ACFastCharging wird dann der 2. Filter noch angewandt.

Und wenn das immer noch nicht das gewünschte raus bringt, so ist der Fehler in der OCM API zu suchen. Das meinte ich doch damit.. Die Logik ist so in Ordnung.

**Comment by secuder** [comment]
Hm, tut mir leid, ich habe vor ziemlich vielen Jahren mal Pascal gelernt, das kann ich so nicht beurteilen. 
Aus User Sicht sind die Ergebnisse nicht schlüssig, nicht nur wegen der 43kW AC, sondern auch wegen der dann plötzlich angezeigten 20kW DC, die durch die Steckerfilterung und durch die Bedingung >=22kW eigentlich ausgeschlossen sein sollten.

Zu den 43kW Typ 2: Hast du berücksichtigt, dass es in OCM offenbar zwei Typ 2-Arten (ID 25 und ID 1036) gibt? Wenn man nach Type 2 Anschlüssen filtert, dann müssen beide zugelassen sein.

**Comment by remuslazar** [comment]
@secuder nein, das ist dann wohl der Bug. Typ 1036 wird nicht berücksichtigt. Ist das Typ2 wo das Kabel dran ist, oder? i.d.R. ist ja Typ2 nur Buchse, Kabel muss der Fahrer dabei haben.

**Comment by secuder** [comment]
In der OCM Datenbank gibt es zwei Typ 2 IDs: ID 25 ist offenbar eine Typ 2 Dose (Kabel mitbringen), ID 1036 ist ein Typ 2 Stecker (einfach direkt ans Auto anschliessen). Sieht mir nicht nach einem bug aus. 


FormalName": "IEC 62196-2 Type 2",
      "IsDiscontinued": false,
      "IsObsolete": false,
      "ID": 25,
      "Title": "Mennekes (Type 2)"


"FormalName": null,
      "IsDiscontinued": false,
      "IsObsolete": false,
      "ID": 1036,
      "Title": "Mennekes (Type 2, Tethered Connector) "

(Quelle: [http://api.openchargemap.io/v2/referencedata/](url)

**Comment by remuslazar** [comment]
@secuder hast du mich falsch verstanden, ich meinte, das ist der Bug _in der App_. Das werde ich sicher im nächsten Build korrigieren!

**Comment by secuder** [comment]
Bei dem DC Ladepunkt OCM-45012 verstehe ich nun immerhin zum Teil, warum er trotz <22kW angezeigt wird:
![img_3926](https://cloud.githubusercontent.com/assets/24484266/21463266/f1133c06-c966-11e6-84e9-35a06d3191dd.PNG)

Der ist Level 3 getaggt trotz einer Ladeleistung von nur 20kW. 

Unklar ist mir aber trotzdem, warum der uberhaupt angezeigt wird, denn da gibt es keinen Typ 2 Stecker (und andere Stecker hatte ich in den Einstellungen nicht ausgewählt)

**Comment by secuder** [comment]
Habs gesehen und meinen Comment schon korrigiert :-) aber zu spät :-D

**Comment by remuslazar** [comment]
ist kein Beinbruch! Gute n8! :)
