### ISSUE TITLE
Default Filter Kriterien irreführend?

### ISSUE THREAD

**Issue by helmutnn** [remuslazar/EVPlugFinderPublic#52]
Es werden nicht alle im GE-Verzeichnis vorhandenen Ladestationen angezeigt. Beispiel:

[http://www.goingelectric.de/stromtankstellen/Deutschland/Duesseldorf/Seestern-Fitnessclub-Sued-Hugo-Wilderer-Weg-21/1153/]

**Comment by remuslazar** [comment]
@helmutnn vielleicht weil der Filter "Ohne Anmeldung", der default aktiv ist nach dem 1. install, AN ist?

Klassiker:)

Die Station ist entsprechend getagged

```
 "barrierfree": false,
```

Siehe auch https://api.goingelectric.de/chargepoints/?key=$key&ge_id=1153

**Comment by helmutnn** [comment]
Die Einstellung sollte dann per default aus sein, wenn alle darüber stolpern :). Die wenigsten Ladesäulen funktionieren ohne Anmeldung, auch wenn das Laden wie in diesem Fall letztlich kostenlos ist.

**Comment by remuslazar** [comment]
nein, wenn der Filter "kostenlos" aktiv ist, werden diese wieder angezeigt. Filter default aus ist nicht gut, weil dann z.B. in Stuttgart man erschlagen wird von den vielen EnBW Stationen, die für viele total irrelevant sind (nur 11kW, kein DC, ). Evtl. könnte man den Filter "Laden kostenlos" ebenfalls default AN machen, dann würde der Workaround greifen.

@helmutnn siehe in diesem Zusammenhang auch:

https://github.com/remuslazar/EVPlugFinderPublic/issues/30

Im GE Forum habe ich auch ein "Issue" gemacht. Ist aber schon länger her und da gab es noch kein Feedback. Schade eigentlich:)

**Comment by remuslazar** [comment]
ok, habe es nun re-opened. Kann man sich also Gedanken machen, ob nun beide Filter aktiv macht per default. Weitere Vorschläge, Meinungen?

**Comment by secuder** [comment]
Meiner Meinung nach sollten Filter per default OFF sein. Wenn es zu viele Ergebnisse sind, dann probiert man die Filter aus und es werden weniger Stationen und man stellt dann ein an Filtern, was man üblicherweise braucht. 
Bei mir in der Gegend sind so wenige Säulen, das ein default-Filter kontraproduktiv ist. 

Übrigens: Durch die Kombination von Filtern dürfen es nur weniger, aber nie mehr Treffer werden - so st ist es kein Filtern (oder habe ich da oben was falsch verstanden?)

**Comment by remuslazar** [comment]
eigentlich nicht, das kommt durch einen Bug in der GE Datenbank zustande. Ich habe da ein Workaround eingebaut, was zu genau dieses Verhalten hervorruft. Habe ich hier schon elaboriert, ist auch ein Link zu meinem Bug-Report im GE Forum:

https://github.com/remuslazar/EVPlugFinderPublic/issues/30

Kannst du dort auch gerne sanft "Druck" machen.

**Comment by Graefer** [comment]
O.g. Beispiel (Düsseldorf-Seestern) ist ein gutes Beispiel für die Unlogik der Filter, worüber ich bereits im GE-Forum berichtet habe (http://www.goingelectric.de/forum/goingelectric-stromtankstellen/unlogischer-filter-t11877.html#p230591): Es handelt sich um eine kostenlose Säule, die eine Anmeldung erfordert, der GE-Eintrag ist insofern korrekt. Bei Auswahl des "ohne Anmeldung"-Filters verschwindet die Ladesäule - korrekt. Wenn jetzt zusätzlich der "kostenlos"-Filter gewählt wird, erscheint die Säule wieder. Das kann nicht richtig sein, da ein Filter immer eine UND-Verknüpfung darstellt (@secuder: +1), d.h. mit der Anwahl eines Filters müssen weniger Säulen angezeigt werden. Hier liegt jetzt aber auf einmal offensichtlich eine "ODER"-Verknüpfung vor. Diese Unlogik macht mich fast krank... ;)

**Comment by remuslazar** [comment]
@Graefer nein, es ist keine ODER Verknüpfung, das ist nicht korrekt, was du behauptest.

Folgendes: im aktuellen Build wird, wenn der Filter "kostenlos" auswählt ist, der Filter "ohne Anmeldung" (falls gesetzt) nicht berücksichtigt. Heißt also, es verhält sich so, als wäre der Filter "ohne Anmeldung" nicht gesetzt.

Der Hintergrund: ich bin ausgegangen, dass es keine Ladestationen gibt, welche "kostenlos" und aber gleichzeitig "mit Anmeldung" getagged sind. (und, ja, ich weiß jetzt, dass es auch einige wenige Fälle gibt, wo das jedoch der Fall ist, das hast du ja bereits geschrieben). Und der o.g. Workaround sollte einfach die falsch getaggten Ladestationen im GE Verzeichnis, wo fälschlicherweise der Tag "mit Anmeldung" (im GE Verzeichnis heißt es "barrierefrei") gesetzt ist, in diesem Fall trotzdem anzeigen. Es ist leider eine Tatsache, dass zahlreiche Stationen, z.B. von REWE, wo man definitiv keine Anmeldung braucht, und auch kostenlos sind, falsch getagged sind. Diese würden dann bei dem gesetzten Filter "ohne Anmeldung" und gleichzeitig "kostenlos" nicht angezeigt werden, weil ja die ja durch den "ohne Anmeldung" Filter bereits ausgefiltert werden.

Ich werde mir Gedanken machen, wie man das besser visualisieren könnte und das in einem kommenden Seed implementieren (z.B. Filter "ohne Anmeldung" dann "ausgrauen", damit einem sofort klar wird, dass das dann nicht aktiviert werden kann).

Sobald man im GE Verzeichnis eine Korrektur durchführt und der Flag "barrierefrei" korrigiert, nehme ich gerne den Workaround wieder raus, dann kann man auch beide Filter kombinieren, was aktuell nicht möglich ist.

**Comment by Graefer** [comment]
Zunächst: nichts für Ungut! Wünsche Deinem Projekt nur das Beste!
Ok, "kostenlos"-Filter deaktiviert "ohne Anmeldung"-Filter. Man könnte also bei Anwählen von "kostenlos" auch den "ohne Anmeldung"-Filter auch visuell wieder deaktivieren. Dann würde das Ergebnis wieder stimmen. 
IMHO sollte die Logik der App nicht unter falschen GE-Einträgen leiden. ;)
Zu guter Letzt: kostenlos und mit Anmeldung ist nicht so selten: allein in NRW betrifft das die Ladesäulen von Stadtwerke Düsseldorf und von TankE - insgesamt >75 Ladesäulen. 
Weiterhin viel Erfolg und Kompliment für das tolle Projekt!

**Comment by remuslazar** [comment]
das ist bereits so im neusten Build implementiert
