### ISSUE TITLE
Suche nach Adresse

### ISSUE THREAD

**Issue by helmutnn** [remuslazar/EVPlugFinderPublic#53]
Es sollte eine Möglichkeit geben nach einer Adresse zu suchen.

**Comment by remuslazar** [comment]
@helmutnn reichen die Möglichkeiten aus, die es gibt? Im Suchfeld kann man auch eine Adresse eingeben und es es nur 1 Treffer gibt, so wird gleich das gesetzt.

Use-Case ist aber eher, dass man die Adresse im lokalen Adressbuch hat, dann kann man die mit dem Picker auswählen.

**Comment by helmutnn** [comment]
Welches Suchfeld? Ich habe nicht angenommen, dass das bei Tipp auf das unterste Icon erscheint. Ja, das reicht natürlich.

**Comment by remuslazar** [comment]
![bildschirmfoto 2016-12-23 um 15 02 47](https://cloud.githubusercontent.com/assets/6108134/21455492/e44b4b76-c920-11e6-85eb-07fc1806106f.png)
