### ISSUE TITLE
Checkins are not visible at GE Page

### ISSUE THREAD

**Issue by helmutnn** [remuslazar/EVPlugFinderPublic#59]
Checkins are not visible at GE Page. Oldest checkin was submitted 10 hours ago.

**Comment by remuslazar** [comment]
expected, currently there is no sync, see also the FAQ section: https://github.com/remuslazar/EVPlugFinderPublic/wiki/Check-In-Feature

**Comment by helmutnn** [comment]
This information is a bit hidden in the FAQ. FAQ entry explains why charlogs of GE are not presented in the App. Maybe the title could be changed to stress there is no connection to GE chargelog at all. To report charges to GE you need to authenticate, so there should be a way to enter the GE Account information in the App.

**Comment by remuslazar** [comment]
unfortunately, there is no API for this purpose available. And, btw, saving the credentials in the app is not the right approach, there are already other alternatives (OAuth2, Auth0, ..) available.

**Comment by remuslazar** [comment]
@helmutnn I have just updated the wiki page as suggested..
