### ISSUE TITLE
Nur Schnelllader zeigt, wenn deaktiviert, nur langsame Lader an

### ISSUE THREAD

**Issue by cbrandlehner** [remuslazar/EVPlugFinderPublic#60]
Die Einstellung "Nur Schnelllader" ist klar, da werden nur Ladestationen angezeigt die schnell laden können.
Wenn ich den Filter deaktiviere werden aber nur Ladestationen angezeigt, die langsam laden - anstelle von langsamen UND schnellen Ladestationen.

**Comment by remuslazar** [comment]
das ist aber definitiv nicht so. Wenn man mit dem Filter arbeitet, wird zusätzlich der Radius vergrößert, wo nach Stationen gesucht werden, vermutlich ist das der Grund zur Annahme.

**Comment by cbrandlehner** [comment]
Keine Ahnung warum, konnte es gestern noch reproduzieren - heute nicht mehr. Schliesse den Report.
