### ISSUE TITLE
Buttons auf rechter Buttonleiste schwer auswählbar

### ISSUE THREAD

**Issue by Trancist** [remuslazar/EVPlugFinderPublic#62]
Auf meinem IPhone SE sind die Buttons wie z.B. die Ladesäuleneinstellungen oder auch der Refresh Button auf der rechten Seite nur schwer anwählbar. Ich muss teilweise 3-4 mal draufdrücken bis die Aktion ausgewählt wird und schiebe dann dabei die Karte so leicht auf dem Bildschirm rum oder löse die Zoomfunktion aus.

**Comment by remuslazar** [comment]
@Trancist heißt also, nachdem man in der Karte gezoomt hat bzw. den Ausschnitt verschoben hat, kann man die Buttons besser "treffen"? Kannst du ein Screenshot erstellen, in einem Zustand, wo die Buttons nicht anwählbar sind?

**Comment by Trancist** [comment]
Guten Morgen Remuslazar,
ich habe mal eine Video erstellt, welches das ganze Verhalten mit den Buttons gut demonstriert.
[CIMG0930.zip](https://github.com/remuslazar/EVPlugFinderPublic/files/870617/CIMG0930.zip)

**Comment by remuslazar** [comment]
@Trancist danke für das Video. Dieses Problem wird (hoffentlich) mit dem kommenden Build (heute oder morgen) gelöst sein: die Buttons haben nun eine fixe Größe und sind ohne Abstand angeordnet, sodass die Touch Events nicht an die darunter liegende Karte gehen können (wenn der Touch Mittelpunkt nicht ganz mittig ist), was vermutlich zu diesem Problem geführt hat.
