### ISSUE TITLE
Abgleich von Störungsmeldungen und deren Auflösung

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#64]
Ich habe verstanden, dass die _Check-Ins_ in der APP nicht in das GE-Verzeichnis zurückgegeben werden können. Wie erfolgt aber ein Abgleich zwischen dem Forum und der APP, wenn die Störung behoben ist?

Ich habe am Wochenende eine Störung für den Ladepunkt 9909 (Destillatio in Eiterfeld) im _Check In_ erstellt (und ich dachte auch eine im GE-Verzeichnis, aber es kann sein, dass ich mich da irre, denn in der Störungshistorie finde ich nix dazu). In der APP ist der Ladepunkt noch ausgegraut, im Forum aber nicht (mehr???).

Ich hatte den Betreiber noch am gleichen Tag angerufen; da er selbst dort lädt, hat er wahrscheinlich längst den Ladepunkt wieder in Ordnung gebracht, aber die APP zeigt das nicht.
Gesetzt den Fall, ich hätte die Störung ordnungsgemäß auch im GE-Verzeichnis gemeldet und sie sei zwischenzeitlich beseitigt, hätte das eine Auswirkung auf die Anzeige in der APP? 

Besteht die Gefahr, dass der Datenstand zwischen APP und GE-Verzeichnis bezüglich der Störungen auseinanderlaufen und bis zu welchem Punkt ist das wünschenswert bzw. erträglich?

(Viele Abhängigkeiten in diesem Issue - hat der Betreiber die APP, wann gibt es eine erweiterte API, etc pp - aber ich dachte, ich schreibe das trotzdem mal auf...)

**Comment by remuslazar** [comment]
momentan werden aktive Störungen nach dem „last wins“ Verfahren zusammen geführt. Heißt also, wenn eine Störung aus dem GE Verzeichnis kommt, so wird diese angezeigt, wenn es jedoch eine neuere gibt über die App, dann eben diese. Und Vice versa.

Was nicht vorgesehen ist, dass man z.B. eine Störung in der App meldet und diese dann im GE Verzeichnis „behebt“. Heißt konkret, wenn man eine Störung in der App gemeldet hat, so muss man dort wieder einen positiven CheckIn durchführen, damit die Störung „resolved“ wird. Dann (und erst dann) werden auch die entsprechenden Push Nachrichten versendet.

Mit dem (i) kann man ja auch in der App die CheckIn Historie ansehen, so kann man gut sehen, ob die Meldung über die App gemacht wurde oder aus GE kommt:

<img width="394" alt="checkin_i" src="https://cloud.githubusercontent.com/assets/6108134/25718377/1813aafa-3106-11e7-97f5-3fef81e7de25.png">

**Comment by secuder** [comment]
Das heißt, wenn der Betreiber kein iPhone hat, dann bleibt die Störung auch dann in der APP bestehen, wenn es positive Einträge _(erfolgreich geladen)_ im GE-Verzeichnis gibt? Vielleicht könnte man die ebenfalls im "last win" System auswerten?

**Comment by remuslazar** [comment]
nein, das geht technisch nicht. Über die API werden aktuell nur Störungen gemeldet und nur dann, wenn eine Störung aktiv ist. Wenn nicht, kommt auch keine Info, ob es eine gegeben hat und auch kein Timestamp, wann die letzte Störung behoben wurde. Wenn man also eine Störung an Dritte weitergibt, muss man aktuell auch dafür Sorge tragen, dass diese in der App auch als behoben markiert wird, wenn der Dritte nicht auch mit der App arbeitet.. Oder aber, wenn davon auszugehen ist, dass die Störung sowieso automatisch im GE Verzeichnis behoben wird, so kann man diese dann direkt von Anfang an dort eintragen. Diese wird dann auch über die App ausgewertet (dann jedoch ohne Push..)

**Comment by remuslazar** [comment]
Siehe auch http://www.goingelectric.de/forum/goingelectric-stromtankstellen/offizielle-api-t20221-50.html#p512368

**Comment by secuder** [comment]
Hm, verstehe, aber das ist recht unpraktisch. An dem Ladepunkt war ich bei einem Ausflug, dh er liegt nicht auf meiner normalen Strecke. Ob der Owner ein iPhone _und_ die APP hat, weiss ich natürlich überhaupt nicht. Andere APP-Nutzer werden die Ladestation in nächster Zeit meiden, weil es einen Fehlereintrag gibt. Nutzer ohne APP laden vielleicht, aber das nutzt der APP nix. Damit reduziert sich die Chance zur Korrektur enorm. 
Ich kann die Störung natürlich rausnehmen mit dem Kommentar, dass sie beseitigt sein müsste - aber das kann ja auch nicht der Sinn der Sache sein.

**Comment by secuder** [comment]
...ein automatisches Verfallsdatum der Störungen in der APP wäre da vielleicht eine mögliche Übergangslösung.

**Comment by remuslazar** [comment]
ja, ich verstehe die Problematik schon und ich habe die Hoffnung nicht aufgegeben, dass mittelfristig eine bidirektionale Synchronisation mit dem GE geben wird. Bis dahin muss man eben mit diesen Einschränkungen leben.

Wenn die App offiziell im App Store ist, gehe ich davon aus, dass sich die Nutzergruppe stark erhöhen wird. Dann werden Störungen automatisch durch positive CheckIns anderer User "resolved". Wenn man eine gewisse kritische Masse erreicht hat, gehe ich davon aus, dass das gut funktionieren wird, zumal mit der App eine CheckIn sehr effizient durchgeführt werden kann. Auch im GE Verzeichnis sind z.T. Störungen seit 2015 drin bei Ladepunkten, die wohl eher selten angefahren werden. Ich gehe davon aus, dass diese Störungen längst obsolet sind.

**Comment by remuslazar** [comment]
ja, Verfallsdatum werde ich vermutlich schon einbauen, zumindest in der Form, dass diese Punkte dann eben nicht mehr grau dargestellt werden. Die Störung kann dann schon wie jetzt in der Detail View angezeigt werden, mit dem Timestamp, so kann der User die Aussagekraft gut einschätzen..

**Comment by remuslazar** [comment]
relativ unwahrscheinlich, dass die GE API erweitert wird.
