### ISSUE TITLE
Today-Widget: CheckIn an der aktuell nächstgelegenen Ladesäule

### ISSUE THREAD

**Issue by remuslazar** [remuslazar/EVPlugFinderPublic#65]
### Abstract

Die App sollte ein "Today-Widget" anbieten, welches ein CheckIn an der aktuell nächstgelegenen Ladesäule ermöglicht.

### Use-Case

Ich möchte einfach und schnell an einer Ladesäule einen Checkin loggen, ohne dafür die App öffnen, die Location auszuwählen, reinzuzoomen, die Ladesäule auszuwählen müssen.

### Technische Details / Umsetzung

Um im Widget auch die aktuell nächst gelegene Ladestation anzuzeigen, wäre eine Standortsabfrage im Hintergrund notwendig (inkl. der entsprechenden Berechtigung). Um dies zu vermeiden, sollte das Widget lediglich einen Link anbieten, der dann diese Aktion in der App wie folgt triggert:

1. App wird gestartet
2. Standortsabfrage wird durchgeführt (Visualisierung, "cancel"-Button)
3. Check-In Sheet für die jew. Ladestation präsentieren

Sollte sich keine Ladestation in der Nähe befinden, eine entsprechende Fehlermeldung generieren (z.B. modales Dialog)

**Comment by umrath** [comment]
Die Standortabfrage aktiv in das Widget einzubauen, ist keine Option? Also praktisch eine "2 tap to checkin"-Funktion in der Form, dass das Widget mit dem ersten Tap eine aktive Standortabfrage durchführt und mit dem zweiten Tap dann den Checkin durchführt.
Der Vorteil wäre die Geschwindigkeit bzw. die Zeitersparnis, die dieser Ablauf mit sich bringen würde.

**Comment by remuslazar** [comment]
@umrath doch, das ist eine gute Idee! bei dem 1. Tap könnte das Widget auch die z.B. 5 Treffer anzeigen (z.B. mit der Entfernung (Luftlinie)), sodass der Benutzer eine Ladestation aus der Liste auswählen kann.

**Comment by remuslazar** [comment]
Today Widget wurde implementiert und mit Build 40 frei gegeben.
