### ISSUE TITLE
Fehler: Filter "Jetzt geöffnet"

### ISSUE THREAD

**Issue by Graefer** [remuslazar/EVPlugFinderPublic#68]
Hi, offensichtlich hat der Filter "Jetzt geöffnet" ein Problem mit der Art und Weise, wie ein ganztags geschlossener Tag auf GE eingetragen wird (0.00 bis 0.00), denn das wird von der App als ganztags geöffnet interpretiert.

**Comment by remuslazar** [comment]
ich würde sagen, der Eintrag ist einfach buggy bei GE und sollte dort korrigiert werden. Man kann doch auch Tage „komplett geschlossen“ eintragen, dann braucht man auch kein Time Range. Wo tritt das Problem auf?

**Comment by Graefer** [comment]
Der Eintrag ist missverständlich - aber im Sinne der GE-Logik korrekt und auch nicht anders eintragbar. Das Problem betrifft alle Aldi- und Lidl-Ladesäulen.

**Comment by remuslazar** [comment]
@Graefer aber die Filterung macht nicht die App selbst sonder die GE API. Ich glaube, da ist noch ein Bug-Report offen im GE Forum, weil das nicht sauber funktioniert. Die App nutzt die Info lediglich um die Öffnungszeiten anzuzeigen.

**Comment by Graefer** [comment]
Tja, das mag so sein. Mir fällt aber auf, dass in der Ladesäulenbeschreibung der App die Ladesäule korrekt als geschlossen angegeben wird. Das wird dann offensichtlich nicht über das (fehlerhafte) open_now flag der API, sondern über eigenes parsen der eingetragenen Zeiten errechnet? Wenn Du Dir die Arbeit also schon gemacht hast, könnte man ja auch diesen Wert für den Filter nehmen?!

**Comment by remuslazar** [comment]
@Graefer genau, das habe ich mir auch schon überlegt, man könnte einfach ohne Filter fetchen und dann hinterher filtern. Das wäre pragmatisch, um das Problem zu lösen. Ich persönlich bin aber kein Freund davon, in diesem Fall, weil das ja nur ein „Hack“ wäre.

Es ist natürlich nicht ideal, dass offene GE API Bug-Reports so lange „liegen“ bleiben aber genau da sollte man ansetzen. Willst du dich mal in die Richtung engagieren?

**Comment by Graefer** [comment]
Ok, Fehler der GE-API scheint gelöst zu sein.
