### ISSUE TITLE
Kosmetischer Fehler: Elemente werden auf dem iPhone SE verdeckt

### ISSUE THREAD

**Issue by umrath** [remuslazar/EVPlugFinderPublic#69]
Wenn man auf einem iPhone SE eine Ladesäule in der Mitte antippt, wird an der rechten Seite fast immer das "i" und ggfs. Teile des Namens verdeckt.

Hier wäre eine andere Platzierung der Elemente sinnvoll. Ggfs. bietet sich auch an, die Menüleiste vertikal und nicht horizontal anzuordnen.

Beispiel der Verdeckung:
![img_3898](https://user-images.githubusercontent.com/1010437/27605685-b15dffd4-5b7d-11e7-807f-efca6ebfb704.PNG)

**Comment by remuslazar** [comment]
@umrath das "i" hat eigentlich gar keine extra Funktion, lediglich einen informellen Charakter. Man kann auch genauso gut die Annotation selbst "touch"en, da kommt man auch hin.

**Comment by umrath** [comment]
Oh, interessant. Ich habe intuitiv immer versucht, das "i" anzutippen. Wenn das gar nicht notwendig ist, ist das Issue nur ein kosmetisches Problem.

**Comment by secuder** [comment]
Das "i" suggeriert duch die Farbgebung, dass es ein "link" sei, der Titel der Ladestation dagegen ist schwarz.
ME. folgt die Intuition dem automatisch - insofern wäre es es vielleicht im Sinne der Usability wert, das kosmetische Problem zu lösen. (automatische Kollisionsabfrage und Verschieben?)

**Comment by remuslazar** [comment]
@secuder klar, man könnte viel machen. Allerdings werde ich die neuen iOS11 Features bald nutzen, um die Kartendarstellung mit den dortigen Möglichkeiten zu erweitern. Dann wird man auch nicht mehr so eingeschränkt sein wie aktuell im iOS10 und dabei werde ich auch dieses Problem adressieren.

Daher mache ich das erst mal zu.
