### ISSUE TITLE
Check in und Ladelog

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#70]
Hallo Remus,
vielleicht sollte man den von Dir [hier](https://github.com/remuslazar/EVPlugFinderPublic/wiki/Check-in-Feature-Reloaded#begrifflichkeit) überlegten "Check in" einfach "Logbuch" nennen - das wäre einfach und verständlich, keiner erwartet ein "Check out".

Das Logbuch könnte man in einen öffentlichen Teil (die aktuell im Check in verwendeten Daten werden eingetragen, im Wesentlichen ob es funktioniert hat oder nicht und der TimeStamp) und einen privaten Teil aufteilen, die aber beide gemeinsam erstellt werden. Für den User zB umsetzbar: Oberer Teil des Screens sind die öffentlichen Daten, unterer Teil (geeignet zB farblich abgesetzt) die privaten Daten wie von Dir [hier beschrieben,](https://github.com/remuslazar/EVPlugFinderPublic/wiki/Check-in-Feature-Reloaded#eigene-ladepunkte) als optionale Eingaben. 

Vorteil: Nur ein Logvorgang, klare Benennung
potentieller Nachteil: Verwirrung, was nun öffentlich und was privat ist - das sollte sich durch ein geeignetes User-Interface vermeinden lassen.

**Comment by secuder** [comment]
ach ja, für das Anlegen von eigenen Ladepunkten: Die Koordinaten sollten bei der Erstellung von der aktuellen Position übernommen werden können (aber das hättet Du sicher sowieso so gemacht...)

**Comment by HaraldWalker** [comment]
Eigentlich würde ich mir checkin und checkout wünschen, so dass ich ein komplettes Log habe. Wenn ich dann noch extra Daten wie SOC (an/ab) und Kw eintragen kann, wäre es perfekt und kann man es später benutzen um Statistiken zu berechnen und die Abrechnungen die ja oft erst Wochen später kommen zu kontrollieren.

**Comment by Graefer** [comment]
Dass man bei Anklicken von "Fotos" und "Standortdetails abrufen" zu weiteren Infos kommt, aber abweichend davon beim Ladelog über das "i"-Zeichen, ist inkonsistent. Ich würde a) das Verhalten angleichen (Anklicken führt zu Infos) und b) das "i" durch ein Stift-Symbol ersetzen und damit in den Ladelog-Schreibmodus wechseln. 
PS: Wenn es "Standortdetails abrufen" heißt, sollte vielleicht auch bei Fotos ein Verb stehen, also "Fotos ansehen" heißen.

**Comment by gerritvanaaken** [comment]
Die "Doppelbelegung" für "Ladelog angucken" und "Ladevorgang eintragen" ist wirklich unglücklich. Im Grunde genügt der Button "Eigenen Ladevorgang eintragen" auf der Seite mit dem Ladelog, ganz oben.

**Comment by remuslazar** [comment]
@gerritvanaaken, @Graefer ich habe das nun umgebaut, wie im folgenden Screenshot sichtbar:

![bildschirmfoto 2017-08-17 um 20 14 50](https://user-images.githubusercontent.com/6108134/29427024-c405bbe4-8388-11e7-81a2-1a83c7d56710.png)

Die Funktionen (zeige Liste und add checkIn) sind nun vertauscht. Ich denke, das ist so auch intuitiver bedienbar, ohne in der UX noch eine weitere "Action" Zeile hinzuzufügen. Ich wollte das kompakt halten.

**Comment by gerritvanaaken** [comment]
Viel besser!

**Comment by Graefer** [comment]
Prima.

**Comment by remuslazar** [comment]
Wurde so mit Build41 implementiert.
