### ISSUE TITLE
Bilder cachen?

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#71]
Wenn man sich die Fotos der Ladestation anschaut, werden sie geladen. Geht man dann zurück auf die Seite mit den Ladestation-Infos und nach kurzer Zeit noch mal auf die Fotos, so werden sie neu geladen. Bei schlechtem Netz ist das eine Qual.

Kann man die Bilder für eine gewisse Zeit cachen?

**Comment by remuslazar** [comment]
ja, das ist bereits so vorgesehen. Das Caching übernimmt dabei die Komponente, welche das „Download“ macht, konkret „URLSession“, dort wurde die Session bereits so konfiguriert, dass diese Daten gecached werden sollen.

Ich habe auch mal gerade getestet: das funktioniert schon: wenn ich das gleiche Bild ein 2. Mal ansehe, so wird auch nicht das Bild übertragen, lediglich ein Paar Meta-Informationen. Wenn der Server meldet, dass sich das Bild seit dem letzten Aufruf nicht geändert hat, so wird auch das Bild aus dem Cache genutzt. Dabei werden die ETag's genutzt, die werden aber von GE auch korrekt gesetzt, wie ich empirisch validieren konnte.
