### ISSUE TITLE
Entferungen werden nicht automatisch aktualisiert

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#72]
ich befinde mich an einer Position A und lasse mir Ladestationen im Umkreis anzeigen. Ich fahre ein Stück zu Position B. Die für mich möglicherweise interessanten Ladestationen werden immernoch angezeigt, der Positionsmarker hat sich bewegt.
Wenn ich nun Ladestationen aufrufe, so wird weiterhin die Entfernung zu Position A angezeigt, obwohl ich mich inzwischen ja wo ganz anders befinde.

Es sollte immer die Entfernung zur aktuellen Position errechnet und angezeigt werden.

**Comment by remuslazar** [comment]
@secuder das Problem tritt nur auf dem iPad auf, oder? Wo man die Liste parallel zu der Karte anzeigen kann.

**Comment by remuslazar** [comment]
Falls dem so ist, so sehe ich nicht den Bedarf, das zu ändern. Die Liste ist ja "modal", während die Liste geöffnet ist kann man gar keine weitere Action in der App vornehmen. Klar, kann sich die Position im Hintergrund bewegen, die Liste sollte jedoch weiterhin statisch sein. Das wäre ziemlich verstörend, wenn sich laufend die Labels ändern und ggf. auch die Sortierung - weil die Liste nach Entfernung sortiert ist, das müsste man dann auch nachziehen.

Das ist auch kein Use-Case der App. I.d.R. wird man die Liste aufmachen, dort ggf. einen Eintrag auswählen, die Liste sollte nur für eine relativ kurze Zeit aktiv sein.

**Comment by secuder** [comment]
Hallo Remus,
iPhone6S
Für mich war es ein usecase und es hat mich gestört ;-)  
Ich glaube, das war so: Anhalten, Grobplanung - was ist erreichbar und auf dem Weg (durchaus in 30km Entfernung). Dann nach 20km Auswahl des Ladepunktes und irritiertes Gucken, weil die Reichweite ja gar nicht mehr passt für die (nicht aktualisierte) Entfernung.

**Comment by remuslazar** [comment]
das heißt, die Liste war offen, während man 20km gefahren war?

**Comment by secuder** [comment]
ist nun schon eine Weile her, aber ich denke mal: ja. Wahrscheinlich hatte ich das iPhone während der Fahrt ausgedrückt
