### ISSUE TITLE
Anzeige bei Störung

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#73]
Grundsätzlich ist es praktisch, wenn eine Störung durch eine graue Pin angezeigt wird. Ungünstig ist das dann, wenn nur einer von mehreren Steckern nicht funktioniert. 

Ich habe leider auch keine gute Idee, gestreifte Pins werden ja nicht gehen...

**Comment by secuder** [comment]
![img_5096](https://user-images.githubusercontent.com/24484266/27984694-89fa4bde-63dc-11e7-846e-a1e946e86d17.PNG)
![img_5097](https://user-images.githubusercontent.com/24484266/27984693-89f9edba-63dc-11e7-916c-fcaec37352cb.PNG)

**Comment by Graefer** [comment]
Man könnte grundsätzlich jedem Ladestecker einen Pin geben. Das würde natürlich unübersichtlich werden.  Darum: auf den grauen Pin klicken und bei den Details gucken, was los ist - ist doch ok so.

**Comment by remuslazar** [comment]
ja, sehe ich auch so. Auch wenn das "gestreift" ist, so wird man trotzdem nachsehen müssen, was genau defekt ist.

Außerdem kennt die GE Datenbank keine Unterscheidung nach Ladestecker, das steht nur in der Beschreibung. Daher kann sowas auch technisch nicht umgesetzt werden, da die App auch die Information aus der GE Datenbank vereint.

**Comment by secuder** [comment]
"Getreift" hat den Vorteil, dass man weiß, es geht was - und schaut nach, ob der passende Stecker geht. 
Grau wird als "defekt==uninteressant" wahrgenommen und gleich (womöglich unberechtigt) aussortiert.

Aber wenn es nicht geht, dann geht es nicht...
