### ISSUE TITLE
Show selected values for radius sliders

### ISSUE THREAD

**Issue by HaraldWalker** [remuslazar/EVPlugFinderPublic#74]
The slider for 'Fetch radius/number of stations' and 'proximity radius' does not show what value has been or is actually being set.

To improve usability it should provide visual feedback to the user. 

![evplugfinder-settings](https://user-images.githubusercontent.com/2520109/28539119-e79727ae-70b0-11e7-8d0c-a3181f41f54f.png)

**Comment by remuslazar** [comment]
I agree to some extent, unfortunately this feature cannot be implemented for a „App Preferences Slider“ element, the current API simply does not support this feature.
