### ISSUE TITLE
Nutzung des persönlichen Ladelogs

### ISSUE THREAD

**Issue by Graefer** [remuslazar/EVPlugFinderPublic#75]
Es wäre schön, wenn man die eigene Ladehistorie anhand einer chronologisch sortierten Listenansicht des persönlichen Ladelogs anzeigen könnte (und ggf. exportieren). 

Und könnte man die unbelegten Plätze der manuellen Favoritenliste nicht automatisch durch die (nach persönlichem Ladeblog) am meisten genutzten Ladesäulen auffüllen?

**Comment by remuslazar** [comment]
siehe hierzu auch:

https://github.com/remuslazar/EVPlugFinderPublic/wiki/Check-in-Feature-Reloaded

Da stehen also noch weitere Erweiterungen an, vermutlich erst nach dem offiziellen Release aber.

Zu der Favoriten-Liste: die Begrenzung auf 20 macht aktuell keinen Sinn mehr (weil das Geofencing mittlerweile pro Favorit ein/ausschaltbar ist). Ich werde daher diese Begrenzung in einem zukünftigen Seed aufheben.

**Comment by Graefer** [comment]
Ok!
