### ISSUE TITLE
Unvollständige Anzeige des Namens

### ISSUE THREAD

**Issue by Graefer** [remuslazar/EVPlugFinderPublic#76]
Beim iPhone werden sehr lange Namen von Ladesäulen nicht vollständig angezeigt - weder im Quickinfo-Popup der Karte, noch der Detailansicht (bzw. dort nur im Landscape-Mode). Gerade bei Tank&Rast-Ladesäulen wird kaum mehr als "Autobahnraststätte" angezeigt. 
Könnte man den Schriftgrad bei sehr langen Namen nicht verkleinern, damit sie vollständig angezeigt werden?

**Comment by remuslazar** [comment]
@Graefer das habe ich ja bereits im neusten Build implementiert, der Name wird in der Detail-View unten bei der Adresse angezeigt und auch entsprechend umgebrochen, wenn nötig.
