### ISSUE TITLE
Filter E-Bike

### ISSUE THREAD

**Issue by fschulze** [remuslazar/EVPlugFinderPublic#77]
Would be nice if one could filter out E-Bike only stations. Using a Kangoo Z.E. searching for Schuko is useful, but returns lot's of E-Bike stations. Not sure if it would be better if this is done on the source data side (GE and OCM) with a new flag.

**Comment by remuslazar** [comment]
just leave the existing „Schuko Filter“ OFF (in App Settings) and the app logic will filter out all „e-bike only“ charging stations. Or what exactly is the use-case for this feature request?

**Comment by fschulze** [comment]
If I leave Schuko off, then I won't find any Schuko only stations, even if they aren't E-Bike only.

**Comment by remuslazar** [comment]
But what is your "filter out e-bike only" use case? Schuko is schuko and at least in Germany all Schukos are 16A capable.

**Comment by fschulze** [comment]
As far as I understand E-Bike only and judging from the associated pictures, I wouldn't be able to charge my Kangoo there, because I can't reach it because of size, or it's forbidden for cars.

**Comment by remuslazar** [comment]
.. ok, this is another issue. Both GE and OCM are EV Registries, charging stations not accessible for EV (size, location, policy) should not be listen at all.

**Comment by HaraldWalker** [comment]
They both do. For instance:
https://openchargemap.org/site/poi/details/45190
http://www.goingelectric.de/stromtankstellen/Deutschland/Bohmte/E-Bike-Ladesaeule-Rathaus-Bremer-Strasse-4/21620/
But it an issue of the data-source, so EVPlugFinderPublic can't do anything about it.
