### ISSUE TITLE
Farben der Pins überdenken

### ISSUE THREAD

**Issue by gerritvanaaken** [remuslazar/EVPlugFinderPublic#78]
Ein wiederkehrendes Missverständnis bei vielen "Stationslisten auf Karten" ist die Farbe Rot. Viele Anwender denken instinktiv "rot = nicht verfügbar". Vielleicht kann man da noch einmal drüber nachdenken. (Auch in der Plugsurfing-App steht rot für belegt.)

Warum nicht einfach:

Grün = Top-Speed mehr als 22 kW
Gelb = okayer Speed 11 – 22 kW
Grau = langsamer als 11 kW (wie bei GoingElectric)
Rot = Achtung! (nicht verfügbar, Zeitbeschränkung, kaputt gemeldet usw.)

Diskutieren Sie! ;-)

**Comment by apographon** [comment]
Zu viele Statusinformationen in eine Farbcodierung zu packen ist schwierig.
Wir kennen eine einfache Notation: Grün/Gelb/Rot.
Ich würde stark dafür plädieren, solch ein einfaches Konzept zu verwenden:
- Grün: Alles gut     oder Speed > 11 KW
- Geld: Belegt         oder Speed <=11 KW
- Rot: Defekt

**Comment by remuslazar** [comment]
@gerritvanaaken über die aktuelle Farbkodierung kann man sicher sinnieren. Mit der gleichen Farbe 2 Eigenschaften zu „vermengen“, @apographon  (belegt _oder_ speed < x) finde ich dagegen nicht sinnvoll.

Konkret Rot mit Grau zu vertauschen wäre dabei sicher eine Option (Grau wird bereits verwenden, wenn eine Ladestation via Check-In als defekt gemeldet ist).

**Comment by gerritvanaaken** [comment]
Verschiedene Bedeutungen vermischen finde ich auch nicht gut. In der Praxis sollte meines Erachtens Rot sehr selten auftauchen, weil man sonst das Gefühl hat, alles ist unter Alarm :-)

**Comment by Graefer** [comment]
Ich finde Gerrit hat Recht. Darum: Rot für Schnelllader (Rot steht für bes. Aufmerksamkeit und Alarm). Grau für "Probleme", Grün für 11-22kW und alles darunter Blau. Nur meine Meinung...

Mal eine andere Idee: Könnte man nicht auch den Benutzer die Farben für die verschiedenen Ladestärken in den Preferences verändern lassen? Die farbliche Unterscheidung zwischen 11kW und 22kW ist für Leute mit 32A-Drehstromlader wichtig, für z.B. eGolf-Fahrer aber völlig egal. 
Zugegeben etwas aufwändig und vielleicht etwas für Version 2.0 ...

**Comment by remuslazar** [comment]
Farben via Preferences verändern halte ich für keine gute Idee. Unterscheidung ob Drehstrom Lader oder nicht wird bereits bei dem Schnellladefilter so berücksichtigt, das habe ich auch bereits im GE Forum erklärt; wie das funktioniert. Ich glaube aber, das ist mit der Farbe nicht ganz konsistent, das werde ich aber noch gerade ziehen.

**Comment by gerritvanaaken** [comment]
@Graefer: Wenn ich Recht habe, hast du mich dann aber falsch zitiert ;-)

**Comment by remuslazar** [comment]
@Graefer ich habe nun gerade nochmals geschaut und die PIN-Farbe ist bereits konsistent mit der Leistungsklasse, die mit dem eigenen Auto auch kompatibel ist. Das war mal glaube ich früher nicht der Fall, das habe ich wohl mit einem älteren Build bereits gefixt.

Die Bestimmung der Leistungsklasse bezogen auf das eigene Fahrzeug habe ich bereits im GE Forum elaboriert, hier nochmals der Link:

http://www.goingelectric.de/forum/goingelectric-stromtankstellen/neue-native-ios-app-jetzt-mit-ge-anbindung-t20525-130.html#p557407

**Comment by Graefer** [comment]
Hm, ich hab' den Link jetzt nur mal überflogen: "...Hingegen ein Zoe Fahrer, der ja mit 22kW am AC laden kann wird diese [22kW-AC-Ladestation] grün sehen und diese werden auch bei dem Filter entsprechend berücksichtigt..."
Also, wenn ich AC>=22kW in den Preferences einschalte werden 22kW-Lader nicht grün gepinnt, wie Du in o.g. Link beschreibst (aber zumindest korrekt als Schnelllader gefiltert). 

Übrigens: Rot und Orange sind IMHO als Farben sehr ähnlich. Warum nicht noch z.B. Blau nehmen?

**Comment by remuslazar** [comment]
.. ja, es gibt noch eine weitere Einstellung, welche die untere Leistungsgrenze bestimmt, ab wann eine Station als Schnelllader berücksichtigt wird. Aktuell ob ab 20 oder 43kW. Dann sollte der Filter entsprechend filtern und auch die Farbe entsprechend gesetzt werden.

**Comment by remuslazar** [comment]
Blau ist ungünstig weil auch der Karte viele blaue Elemente gibt, sodass man die Pins nur noch schlecht erkennt. Ich habe damals schon einige Farben ausprobiert.

**Comment by remuslazar** [comment]
@gerritvanaaken Hier ein Screenshot, wie es mit grauen und mit roten Pins aussieht im Vergleich:

![bildschirmfoto 2017-08-19 um 09 37 09](https://user-images.githubusercontent.com/6108134/29484579-2b65a670-84c2-11e7-9f35-89393e142b4c.png)

![bildschirmfoto 2017-08-19 um 09 37 49](https://user-images.githubusercontent.com/6108134/29484580-2d67540a-84c2-11e7-807e-79679b6c4308.png)

Ich finde die roten Pins passen besser. Graue Pins gehen einfach unter, die kann man visuell nicht so gut wahr nehmen. Grau ist IMO ok, wenn man, wie aktuell, defekte Ladesäulen taggen will, wenn es zu viele graue Pins auf der Karte gibt, sieht das nicht gefällig aus.

Was meint ihr?

**Comment by gerritvanaaken** [comment]
Interessanterweise denke ich genau andersrum: Zuviel Rot auf der Karte ist mir zuviel Alarm, wenn doch einfach nur sehr langsame Ladesäulen gemeint sind.

Für die obere Version spricht, dass sie visuell ruhiger ist, den Fokus auf die "guten" Stationen legt, und wenn da ein oder zwei rote Pins für kaputte Stationen dabei sind, dann sind das ja wertvolle Hinweise, falls man beispielsweise tatsächlich geplant hat, genau diese Station anzufahren.

Für die untere Version spricht, dass die Farblogik in sich stimmiger ist: Farbige Stationen funktionieren grundsätzlich, graue sind kaputt. Innerhalb der Farben ist der Speed von "okay" bis "naja" hin zu "langsam" auch alles stimmig.

Es destilliert sich auf eine Fragestellung hin:

- Wollen wir vor Schuko-Steckdosen aktiv warnen?
- Oder sind Schuko-Steckdosen einfach nur langweilig?

**Comment by remuslazar** [comment]
@gerritvanaaken vielen Dank für das fundierte Feedback. Zu der (aktuellen) Farbgebung:

Ich habe bewusst die "Ampel-Farben" gewählt - mit einer leichten Abwandlung (anstatt Gelb habe ich Orange gewählt), aus den folgenden Gründen:

* die Farben setzen sich von den sonstigen Farben auf der Karte ab (Blau und Gelb waren ungünstig)
* die Zielgruppe kommt mit der Semantik zurecht

Zu der Semantik hatte ich die folgende Überlegung:

* grün: schneller Ladevorgang, die "Ampel" steht hier auf "grün", man kann gleich also weiter fahren
* rot: niedrige Ladegeschwindigkeit, also **Destination Charging**, Ampel auf "rot" weil das eben "Ziel/Ende" ist. Hier legt man eine längere Pause ein, z.B. Ladung über Nacht. Analog Routing, hier ist auch das Ende immer rot.

Ich muss zugeben, ich habe auch immer so geschaut, wenn ich eine Route geplant habe: Unterwegs immer nach grün gesucht, am Ziel war dann rot passend. Ich habe oft mit dem iPad meine Route geplant, mit dem Split View, rechts hatte ich die Route und links eben EVPlugFinder.

**Comment by gerritvanaaken** [comment]
Also, ich bin voll okay mit deiner Argumentation. Es war aber gut, mal drüber gesprochen zu haben!

**Comment by Zoelibat** [comment]
Hi, ich würde ebenfalls rot als Störung interpretieren. Rot bedeutet für mich wie auch für viele andere, dass erhöhte Aufmerksamkeit erforderlich ist bzw. dass es sich um einen Fehler handelt (oder stehenzubleiben, um bei der Ampel zu bleiben).

Ich denke, dass blaue Pins ebenfalls gut sichtbar sind auf der Karte, kann auch violett oder schweinchenrosa sein. ;-) Rot und Orange sind auf jeden Fall schwieriger untereinander zu unterscheiden.

**Comment by Graefer** [comment]
Rot sollte besondere Aufmerksamkeit auf sich ziehen: das sollte für die wenigen und wichtigen Schnelllader vorbehalten sein. 

Grau ist schlecht zu sehen - und gerade darum ideal für Ladesäulen, die nicht zu benutzen (defekt) sind.

**Comment by remuslazar** [comment]
@Graefer ich habe die Semantik weiter oben elaboriert, insbes. warum Rot für "Destination Charger" gewählt wurde.

@Zoelibat Ich finde die Unterscheidung zwischen Rot und Orange ausreichend. Orange ist im Prinzip (je nach Auto, wenn man nicht gerade ein Tesla fährt) auch "Destination Charger", da ist die "Nähe" zu Rot durchaus beabsichtigt. Und auf meinen iOS Geräten, wo ich die App installiert habe (verschiedene iPads und ein iPhone 7 Plus) kommt das Rot ziemlich "knackig" rüber, das Orange auch. Auf ältere Geräte kann die Farbe durchaus abweichen., das sehe ich jetzt aber auch nicht als grundlegendes Problem.

@all Ich habe aufmerksam "zugehört", habe mich nun entschieden, die Farbgebung (vorerst) so zu belassen wie sie aktuell ist.
