### ISSUE TITLE
Enhancement Request: List of nearby NEW charging stations

### ISSUE THREAD

**Issue by cbrandlehner** [remuslazar/EVPlugFinderPublic#79]
I am using Plugshare as well and found myself regulary checking the list of new charging stations in Plugshare. I am hoping to see this feature based on GE data.

**Comment by remuslazar** [comment]
The GE API doesn't support this kind of queries currently. I'm also not sure if this kind of functionality should be integrared into this app, everything in the app is location/map based and I also want to keep the app focused, though.
