### ISSUE TITLE
store login details in APP?

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#8]
In the details for each loading point there are links to openchargema.org, where one can add comments or photos.
It would be great if user name and PWD could be stored in the APP. This would be a better user experience and lowers the bar for data base enhancements.

**Comment by remuslazar** [comment]
@secuder basically this already works. Just enter the credentials in Safari and the credentials will be just used for the Login using the Safari Autofill feature.

Unfortunately the API does not handle login stuff, so I cannot offer a more native UX for e.g. adding a new charging station. Using the system Safari is the only way to go here, sorry!
