### ISSUE TITLE
Icons Redesign?

### ISSUE THREAD

**Issue by gerritvanaaken** [remuslazar/EVPlugFinderPublic#80]
Bei den fünf Icons rechts oben sehe ich noch Optimierungsbedarf. Ich könnte da mal einen einheitlicheren Entwurf machen, vektorbasiert. Interesse daran? (Hab ein bisschen Erfahrung mit Icons...)

**Comment by remuslazar** [comment]
@gerritvanaaken das klingt gut, gerne! In diesem Zusammenhang wäre auch das App Icon etwas, was sicher noch verbesserungswürdig wäre..

**Comment by Zoelibat** [comment]
Das App Icon bräuchte wirkliche ein etwas moderneres/frischeres Design, vor allem vor der Veröffentlichung im App-Store.
