### ISSUE TITLE
GE "Standortdetails abrufen" -> https

### ISSUE THREAD

**Issue by noelk** [remuslazar/EVPlugFinderPublic#83]
Hallo,

die GE Standortdetails werden per Browser/Safari mit http angezeigt.
Schön wäre es, wenn die App https für diese URLs nutzen/bevorzugen würde.

Vielen Dank.

**Comment by remuslazar** [comment]
warum? Das sind doch lediglich public Informationen, die dort angezeigt werden. Warum sollte man das verschlüsselt übertragen?

**Comment by noelk** [comment]
korrekt, aber in einem öffentlichen WLAN oder bei Massenüberwachung ist damit herausfindbar wer sich für welche Standorte interessiert. Darum werden auch möglichst öffentliche Daten https verschlüsselt (heise.de, ...), damit der zwischen Client und Server lauscht nicht die Interessen/Standorte mitbekommt.
Kann man bestimmt noch besser erklären/begründen, aber ich hoffe der Punkt ist ein bisschen klarer geworden

**Comment by remuslazar** [comment]
ok, aber dann ist die App der falsche Ort, um sowas zu "enforcen", das muss schon die Website tun. Das ist ja bei den Beispielen, die du genannt hast, auch schon so. Wenn man auf "www.heise.de" zugreift, also mit "http", macht die Website ein Redirect auf https://www.heise.de

Der Redirect müsste dann die GE Website auch so in der Art implementieren und das würde in der App auch so auf Anhieb funktionieren.

Wenn man auf die Going Electric Website mit https:// zugreift sind auch alle Links http://, das ist auch etwas, was man dort adressieren müsste.
