### ISSUE TITLE
Feature: Tankstellen im Umkreis einer Route

### ISSUE THREAD

**Issue by F3000** [remuslazar/EVPlugFinderPublic#84]
Hallo , 

hier mal ne Idee : 

Angabe der maximal erreichbaren Reichweite des eigenen Autos in den App einstellungen. Wenn Route berechnet wird , sucht das App automatisch passende Tanskstellen aus die entlang der Route liegen , und noch erreicht werden können. :)

**Comment by remuslazar** [comment]
Da die App aktuell keine Routing-Funktionalität anbietet (A nach B) sondern lediglich die Route zu einer bestimmten Ladestation, kann dies so nicht implementiert werden. "Routenplaner" ist sicher etwas, was man in einer späteren Version machen könnte, das steht jedoch aktuell nicht im Fokus.

**Comment by medoingthings** [comment]
Gibt es mittlerweile Ambitionen in der Richtung? Ich finde ChargEV immer noch die beste App zum Thema. Danke dafür! Allerdings nutze ich sie meist, wenn ich weite Strecken fahre. Aktuell muss ich mir die Route dann merken, die Autobahnen manuell "entlanggehen" und schauen, wo geeignete Stationen sind. 

Da wäre es extrem praktisch, wenn man eine Route angeben könnte und entlang der Route direkt ein passendes Set von Ladestationen hätte.

**Comment by Wordcrafts** [comment]
Ein eindeutiges JA. Wir haben schon einige interne Betas durch, in denen das enthalten ist und polieren gerade die UI. Allerdings muss das Feature mit anderen coolen neuen Features gut zusammenspielen, die wir auch demnächst bringen, was die Sache etwas verzögert und komplexer macht. Kommt bald!
