### ISSUE TITLE
Externe Links umwandeln in Nativ

### ISSUE THREAD

**Issue by F3000** [remuslazar/EVPlugFinderPublic#86]
Hier noch ein Verbesserungsvorschlag:

In der Detail Übersicht jeder Tankstelle kommt man über externe Links  z.b. zum Foto hochladen. 

Könnte man das nicht direkt implementieren ohne das man Safari öffnen muss ?

**Comment by remuslazar** [comment]
das geht nicht, weil die GE API die entsprechende Funktionalität nicht anbietet. Photos können jedoch hochgeladen werden (Plus-Icon bei den Photos). Diese stehen aller User der App zur Verfügung, werden jedoch bei GE nicht angezeigt (s.o.)
