### ISSUE TITLE
Push Nachricht Ladesäule zu früh / zu häufig

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#87]
Die Push Nachricht über das Erreichen einer Ladesäule kommt sehr früh (obwohl ich den Radius auf den kleinstmöglichen Wert gestellt habe) und für die gleiche Ladesäule mehrfach.

Könnte man den Radius weiter verringern und eine zweifache Meldung verhindern?

**Comment by remuslazar** [comment]
nein, beides geht technisch nicht. Die App ist gar nicht daran involviert, die Nachricht sendet das iOS, ohne die App daran zu involvieren. Sonst müsste die App auch "location always" anfordern, was ich aber nicht will.

Ich kann nur sagen, dass mit einem neueren iPhone (hier iPhone 7 Plus) die Nachricht recht zuverlässig kommt und erst wenige Sekunden VOR dem Erreichen der Ladesäule. Ältere Hardware bzw. je nach Privacy-Settings und Netzabdeckung in der jew. Region können natürlich ein anderes Verhalten haben. Apple sagt hier, dass der Radius bis 800m groß sein DARF. Der minimale Radius, also 150m ist eher eine Empfehlung als eine starre Vorgabe am System.
