### ISSUE TITLE
„Top notch“ support auf iPhone X 

### ISSUE THREAD

**Issue by F3000** [remuslazar/EVPlugFinderPublic#89]
App anpassen für den iPhone X Start am Freitag : 

https://designcode.io/ios11-iphone-x
Hier mal ein kleines Beispiel :)

**Comment by remuslazar** [comment]
Die App nutzt jetzt bereits durchgehend Auto-Layout und die Layout-Guides, mit dem "Top notch" gibt es vermutlich keine Probleme. Ich werde mir jedoch die App im Simulator in den nächsten Tagen ansehen, ob Anpassungen notwendig sind und diese mit der kommenden Version (evtl. morgen Abend schon) pushen.

**Comment by F3000** [comment]
Sehr gut . Ich gebe dann Freitag Feedback von dem echten Gerät :)

**Comment by F3000** [comment]
![img_0003](https://user-images.githubusercontent.com/8161283/32395486-a0cc3784-c0e1-11e7-8fff-69d78dcfa29a.PNG)


Also die App ist leide rnoch nicht richtig angepasst . Die Top Notch erscheint gar nicht . Die Ohren sind auch nicht zu sehen

**Comment by remuslazar** [comment]
das klappt schon, nur das aktuell verfügbare Build ist noch mit der alten SDK kompiliert, deswegen läuft das in "compatibility mode". Ich werde am Wochenende noch ein Build raus bringen, u.a. auch mit iPhoneX Fullscreen-Support..

**Comment by F3000** [comment]
Hört sich gut an :) 

Was werden noch für Änderungen kommen ?

**Comment by remuslazar** [comment]
Erledigt mit dem neusten Build (47)
