### ISSUE TITLE
Legend unclear

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#9]
> _3.	siehe http://remuslazar.github.io/EVPlugFinder/, ich habe die Legende dort dokumentiert. Aber ja, ich werde vermutlich eine kurze "Hilfe" zu der App programmieren, welche man bei Bedarf ein und ausblenden kann. Dort kann ich das und auch den Hinweis auf die Settings unter bringen_

according to http://api.openchargemap.io/v2/referencedata/ green should indicate >40kW, this includes also 43kW AC, not only 50kW DC as shown above. ;-)

**Comment by remuslazar** [comment]
I agree, the legend is not quite accurate but otherwise it will be just to hard to understand it, while supplying the OCM implementation details.. In OCM the "level" class is just a separate property, you can tweak it while creating new entries. So e.g. die ALDI Charging Stations here near-by are some tagged as "level3", some as "level2" and some as "unknown". So I have to use some weird heuristic to just display the right color in some cases.. this is definitely something I will have to refine..

**Comment by secuder** [comment]
I just considered all the ZOE Q210 drivers on the goingelectric-forum....

(ZO Q210 is the only car which can use 43kW AC and there is a huge discussion on this all day :-) - but this group of users should be interesting for you, as well.

> In OCM the "level" class is just a separate property, you can tweak it while creating new entries.

The question of the best database is something you have been confronted with already. I do not know how difficult it is to establish a link to a second database and allow the user to choose for himself the database. According to my experience (which is still limited as I normally do not drive much farer than 100km) the goingelectric database is much more complete and accurate. This certainly might be a new "Issue"... :-)
I do not know how many potential users are in that forum, but if you follow their discussions carefully, you see that their database is the one which is used by a great majority, also in the _Tesla Fahrer und Freunde_ forum, see http://www.goingelectric.de/forum/ladesaeulen-status/umfrage-beliebte-verzeichnisse-t19790-20.html?hilit=umfrage%20verzeichnis#p420508

**Comment by remuslazar** [comment]
@secuder you're right, yes. Currently I'm already testing the GE API, everything looks promising..

So.. hold on, personally I'm not married to OCM, this was back then just a pragmatic decision I made...

**Comment by remuslazar** [comment]
Superseded by #5
