### ISSUE TITLE
Hilfetexte Farbcodierung

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#90]
Der Hilfetext für die Farbcodierung ist (aus Sicht eines ZOE Fahrers :) nicht richtig:

Grün: Schnell-Lader gibt es auch für AC (dann üblicherweise mit 43kW). Hier solltest Du auf den Zusatz "(DC)" verzichten.

Orange: Sehr oft sind das 11kW AC Lader, der Hinweis auf 6kW Ladeleistung ist mißverständlich.

Die Ladezeiten hängen nicht nur von der angebotenen Ladeleistung und der Lademöglichkeit des Fahrzeugs ab, sondern auch noch von der Größe der Batterie - insofern würde ich auf die Angabe einer Ladezeit verzichten. Für meinen ZOE sind beide Angaben falsch, für einen Tesla wahrscheinlich auch, und auch für den LEAF, falls der grüne Pin eine einsame 43kW AC Ladesäule markiert :)

**Comment by remuslazar** [comment]
Ja, das sind einfach grobe Richtwerte, die angegeben werden. Die Hilfe wird ja noch komplett überarbeitet und erweitert, Status Quo ist ein erster Wurf sozusagen. Aber ja, danke für den Hinweis, vielleicht kann man einfach "Anzahl km / h" eher angeben, das korreliert durchaus in Etwa mit der Ladeleistung und nicht so sehr abhängig von der Batterie. Ich will das jedoch auch einfach halten, das soll eher für die Menschen hilfreich sein, die kWh von kW nicht auseinander halten können.., das sollte einfach einen groben Richtwert darstellen, um es in Etwa einzuschätzen. Wenn man sich ja besser auskennt, lernt man ja schnell, was die Farben für das eigene Auto bedeuten.

Wie an anderen Stellen immer wieder betont, arbeitet die Filter-Logik und v.a die "Schnellladefilter-Logik" intelligent und geht nicht nach der maximal verfügbaren Leistung der jew. Säule sondern berücksichtigt die Einstellung, **ob das Fahrzeug am AC schnell laden kann oder nicht**. Daher wird der Leaf-Fahrer die von dir genannte einsame AC43 Säule gar nicht sehen mit dem "Schnellladefilter" und auch wird sie nicht in grün angezeigt. Kannst du einfach mal probieren, einfach in den Settings die "Fahrzeug kann am AC schnell laden" aus machen.

Die Angabe auf ca. 6kW bezog sich auf die "nutzbare" Leistung. Das ist ja in Etwa die Leistung, die ein Leaf/Ioniq(1phasig)-Fahrer auch am AC22 hat, deswegen werden diese Ladepunkte dort orange dargestellt. AC11 sieht ein Leaf-Fahrer dagegen rot.

**Comment by secuder** [comment]
> Wie an anderen Stellen immer wieder betont, arbeitet die Filter-Logik und v.a die "Schnellladefilter-Logik" intelligent und geht nicht nach der maximal verfügbaren Leistung der jew. Säule sondern berücksichtigt die Einstellung, ob das Fahrzeug am AC schnell laden kann oder nicht. Daher wird der Leaf-Fahrer die von dir genannte einsame AC43 Säule gar nicht sehen mit dem "Schnellladefilter" und auch wird sie nicht in grün angezeigt. Kannst du einfach mal probieren, einfach in den Settings die "Fahrzeug kann am AC schnell laden" aus machen.

> Die Angabe auf ca. 6kW bezog sich auf die "nutzbare" Leistung. Das ist ja in Etwa die Leistung, die ein Leaf/Ioniq(1phasig)-Fahrer auch am AC22 hat, deswegen werden diese Ladepunkte dort orange dargestellt. AC11 sieht ein Leaf-Fahrer dagegen rot.

Das ist richtig. Wenn man jedoch _keinen_ Leaf hat, dann stimmt das so eben nicht mehr. Die Hilfe sollte aber fahrzeugunabhängig sein. Ich finde nicht, dass die Logik in der APP geändert werden soll, sondern nur der Hilfetext. Für einen ZOE gilt das von Dir beschriebene so nicht, auch nicht für einen neuen BMW i3.

Deshalb die Änderungsvorschläge oben in diesem Issue.

**Comment by secuder** [comment]
Gerade sehe ich, dass das für einen ZOE Fahrer der Hilfetext noch irreführender ist, als ich zunächst dachte, denn für einen ZOE Fahrer sind die Farben so codiert:

Grün: 22kW oder 43kW (je nachdem, welchen ZOE man hat)
Orange: 22kW
Rot: 11kW dreiphasig (!) _**oder**_ weniger.

Für mich ist das ein Grund mehr, die Farben nicht fahrzeugorientiert zu erklären.

**Comment by remuslazar** [comment]
@secuder ja, das ist offensichtlich so, wie du es oben beschrieben hast. Wenn ich jetzt darüber nachdenke, finde ich das auch nich ideal aus Sicht eines ZOE-Fahrers jetzt.

Gegenfrage: was wäre eigentlich eine gute Einteilung für den Zoe-Fahrer in so einem Fall? Vorschlag:

* Grün: je nach Einstellung, entweder ab 20kW (i.d.R. AC22) oder aber ab 43kW
* Orange: 11kW bis zu der o.g. Grenze (also 20kW oder 43kW)
* Rot <11kW

Ich denke, somit hat man einen guten Überblick, rot bedeutet eigentlich Schuko oder Typ1 einphasig beschaltet und dann orange deckt den mittleren Range ab, Grün ist dann Schnellladung.

**Comment by secuder** [comment]
Knifflig. Wie Du aus den Diskussionen im Forum über Destination-Ladestationen etc weißt, hat da jeder seine eigenen Ideen. Ich würde unterscheiden nach ZOE mit Schnelllader (bis 43kW Ladeleistung) bzw. ohne Schnelllader (bis 22kW Ladeleistung).

für den 22kW ZOE:

- Grün: 22kW+
- Orange: 11kW
- Rot: alles darunter (langweilig, uninteressant, nur für Notfälle)


für den 43kW ZOE [hab ich nicht, muss man ggf. im Forum abfragen]:

- Grün: 43kW
- Orange: 22kW
- Rot: 11kW und weniger

Für mich sind 11kW schon ganz ordentlich - wenn ich in der Stadt parke und einkaufe oder einen Kaffee trinke und nicht hurtig auf Reisen bin. Weniger will ich aber eigentlich nie, denn so ewig trinke ich nicht Kaffee bzw. gehe ich nicht einkaufen. Deshalb vermisse ich für 11kW eine eigene Farbe. Bei dem "Nur Schnelllader" Filter sind sie (verständlicherweise aber dennoch leider) auch schon verschwunden.

**Comment by secuder** [comment]
Das Dumme ist: Für einen i3 sieht die Sache wieder anders aus. Ideal wäre eine Farbcodierung nach den Lademöglichkeiten oder ggf. individuell.
Per Fahrzeugvorgabe hast Du wegen des Pflegeaufwands verständlicherweise ausgeschlossen. Möglich wäre aber vielleicht, dass man die Farben selbst in den Einstellungen einer Ladeleistung zuordnen kann?
...was wäre freilich ein neuer Request und hat mit der Hilfe erst mal nichts zu tun :)

**Comment by remuslazar** [comment]
@secuder mit dem Vorschlag von mir erreicht man das doch genauso, wie du es auch beschrieben hast:

Schalter AC Schnellladermöglichkeit >= 22kW: AN

### 22kW Zoe (neueres Model):

Einstellung Schnellladeleistung: >=20kW

* Grün: >= 20kW (also konkret AC22)
* Orange: 11kW bis zu 20kW (also AC11)
* Rot: sonst

### 43kW Zoe (altes Model):

Einstellung Schnellladeleistung: >=43kW

* Grün: AC43
* Orange: 11kW bis zu 43kW (also AC11 und AC22)
* Rot: sonst

Das ist doch ganz gut so, so hat man das jew. Auto ideal abgedeckt, ohne dass man in der App weitere Features braucht (lediglich die Anpassung, wie ich vorgeschlagen habe oben)

**Comment by secuder** [comment]
Äh, nein.

Ich habe als Einstellung AC Schnellader (>=22kW) ON (grün) und Schnellladen Leistung >=20kW (Häckchen) gesetzt und bei mir sind 11kW Säulen rot.

**Comment by remuslazar** [comment]
Ja, wie ich bereits geschrieben habe:

> lediglich die Anpassung, wie ich vorgeschlagen habe oben

Das muss ich ja noch umsetzen, vorher geht es nicht.

**Comment by secuder** [comment]
Sorry, das hatte ich falsch verstanden :)

**Comment by secuder** [comment]
Die Hilfetexte sind nach wie vor nicht richtig, wenn man einen i3 oder einen ZOE fährt; siehe auch Kommentar im Forum [von Isomeer](https://www.goingelectric.de/forum/post650764.html?hilit=hilfe%20APP#p650764)

**Comment by remuslazar** [comment]
@secuder die Hilfe wird aktuell überarbeitet. Kannst du evtl. hier man zusammenfassen, was da nicht stimmt? Dann gebe ich das direkt so weiter.

**Comment by secuder** [comment]
Durch die Farblogik ist das nicht einfach - siehe oben, es gibt jetzt eine Abhängigkeit vom Knopf "Schnellladen-Leistung" und evtl. auch eine vom Knopf "AC-Schnelllader"(?). Und dann ist die Frage, ob man das mit diesen Abhängigkeiten auffächern will oder ob das verwirrt. 

Ich mache mir Gedanken und schreibe hier was rein.


Für meine Einstellung

**Comment by secuder** [comment]
:-) Eigentlich passt Dein eigener Text vom 5. Nov doch gut - schlicht und einfach. Auf die Ladezeiten würde ich verzichten, denn die hängen davon ab, was das Auto tatsächlich aufnehmen kann und wie groß die Batterie ist.
Auf Hinweise zu DC/AC würde ich aus dem gleichen Grund verzichten, sofern es keine Abhängigkeit vom Knopf "AC-Schnelllader" gibt.

Also:


- Grün: je nach Einstellung in der _Schnellladen-Leistung_ entweder ab 20kW oder ab 43kW
- Orange: 11kW bis zu der o.g. Grenze (also 20kW oder 43kW)
- Rot <11kW

**Comment by remuslazar** [comment]
Ich würde das nicht zu kompliziert machen. Es gibt halt 3 Klassen:

* Grün: schnell (DC)
* Orange: geht so, mittlere Leistung
* Rot: langsam (=destination charging)

Das sollte dem User eine grobe Orientierung geben. Wenn er es genau wissen will, so kann er immer noch die Details der jew. Ladestation sehen und das genauer wissen.

Dass jetzt diese Klasse bei OCM nicht ganz sinnig ist, ist einfach ein anderes Thema, das muss man separat betrachten. Die Hilfe wird auch dahingehend überarbeitet, dass da die Leistungsangabe als sehr grober Richtwert dargestellt wird, weil die Klasse abhängig von anderen Dingen (User Preferences aber auch Auto Besonderheiten, z.B. AC schnellladefähig usw.) bestimmt wird.

**Comment by remuslazar** [comment]
.. das mit <11kW rot stimmt natürlich nicht. Bei mir als Leaf-Fahrer ergibt das i.d.R. folgendes Bild:

* Grün: DC, also max. 50kW, aber auch 20kW, da ich das so in den Settings eingestellt habe (ich will alle DC Lader grün sehen, das ist für mich schnell genug)
* Orange: wo ich mit 6,6kW laden kann
* Rot: alles andere (i.d.R. 3,6kW oder weniger)

Wie ich schon sagte, die Farbe(=Klasse) als Klasse darstellen und gar nicht groß rum reiten auf irgendwelche Leistungsangaben ist besser. Wichtig natürlich, dass das in sich konsistent ist. Was ja aktuell (zum. bei GE, weil dort die Leistungsklasse berechnet wird und nicht redaktionell gepflegt wird) gegeben ist.

**Comment by secuder** [comment]
Das hat sich jetzt (doppelt) überschnitten. Geht natürlich auch ohne konkrete Zahlen, was den Vorteil hätte, dass es auch für OCM irgendwie (aber nicht wirklich) passt. Mir ist es mit den Zahlen lieber und ich halte es auch für noch verständlich.
Das 

> (DC)

solltest Du auf alle Fälle weglassen.

Dass _Orange_ bei dem Leaf eine Ladeleistung von 6,6 kW ergibt, liegt nicht an der Ladeleistung der Säule, sondern am Leaf, der die Leistung der Säule nicht komplett aufnehmen kann - die Pin-Farbe soll aus meiner Sicht über die Säule informieren, und nicht, was das Auto daraus macht. Fahrzeugabhängigkeiten einbauen geht theoretisch, aber das hattest Du mit gutem Grund abgelehnt, da man da mit dem Einpflegen der ganzen E-Autos nicht nachkäme.

**Comment by remuslazar** [comment]
nee, genau das macht doch die intelligente Logik der App. Die Klasse sollte doch besser die Leistung in etwa einstufen, die das Auto konkret auch aufnehmen kann. Wie schnell die Ladesäule ist bringt dem User konkret nichts, wesentlich ist doch nur das, was er auch abgreifen kann!

Und außer ZOEs und ältere Teslas gibt es ja auch kaum Autos, die am AC schnell laden können. Und genau für diese "Sonderfälle" gibt es den entsprechenden Schalter. Das nutzt die App dann, um die Leistungsklasse zu ermitteln (=Farbe).

Du musst mich falsch verstanden habe. Ich habe nicht abgelehnt, fahrzeugabhängige Settings zu haben (genau das bewirkt aktuell die "Kann am AC schnellladen Setting" - der Zoe Fahrer stellt hier "ein" und alle anderen "aus". Ich habe lediglich abgelehnt, dafür einen Konfigurator zu bauen und warten zu müssen. Die Gründe dafür habe ich bereits elaboriert.

**Comment by secuder** [comment]
Jupp, hatte ich schon so verstanden, denn dann braucht man den Konfigurator, damit die Hilfe passt.

Neben dem Tesla und den vielen (!) ZOE gibt es den i3 mit 11kW (verkauft sich auch gut). Ich persönlich erwarte auch, dass es zukünftig mehr Autos gibt, die mit 11kW AC laden können, denn je größer die Batterie, desto wichtiger ist eine halbwegs flotte und gängige Ladeleistung für die Nacht - sonst wird der Akku womöglich gar nicht mehr voll über Nacht. 
Es gibt auch neue Entwicklungen wie den neuen Conti-Lader, der soll DC und AC richtig schnell können. Der ist im Markt noch nicht aufgetaucht, aber der wäre was..!

Es ist freilich Kaffeesatzleserei, was sich durchsetzt. 

Für viele ist die Aussage "Orange = 6,6kW" falsch. Falsch ist auch "Grün = (DC)". Dann lieber ohne Zahl und bitte ohne das wirklich verwirrende DC. 

Deine APP, also Deine Entscheidung ;-)
