### ISSUE TITLE
Feature : Fahrzeugspezifische Einstellungen 

### ISSUE THREAD

**Issue by F3000** [remuslazar/EVPlugFinderPublic#91]
Folgenden Vorschlag hätte ich : 

In den Einstellungen gibt es ein neues Menü . Dort werden alle aktuellen Fahrzeuge aufgelistet (i3, Leaf, Tesla) etc . 

Wählt man eins aus , werden automatisch passende Einstellungen wie z.B Schnelllade Spannung ausgewählt . Im weiteren könnte das dazu führen dass z.B sich die Pin-Farbe ändert. 

Mit anderen Elementen könnte man es in Zukunft erweitern :)

**Comment by remuslazar** [comment]
Genau der Vorschlag hatten wir intern auch schon, wir haben uns dagegen entschieden. Hier die 2 Gründe, welche dagegen sprechen:

- Wartungsaufwand ist nicht unerheblich, da kommen ja neue Autos hinzu und da gibt es schon aktuell eine Vielzahl an Optionen und Möglichkeiten, auch z.B. je nach Baujahr etc., das wird ganz schon komplex, wenn man das gut macht. Und mit der Zeit wird das immer größer, weil man immer einen gewissen "Legacy-Part" mitschleifen muss.
- Wenn der Benutzer die - aktuell lediglich nur eine einzige Einstellung "Fahrzeug kann am AC schnell laden ja/nein" - manuell setzen muss, so versteht er auch besser, warum das notwendig ist und was diese Einstellung bewirkt.

Ich will nicht ausschließen, dass der Konfigurator nicht später kommt, das hat jedoch aktuell keine Priorität.

**Comment by F3000** [comment]
ok alles klar verstehe . Und nach Herstellern sortiert ? 

Ich gehe mal davon aus , dass wenn BMW 2019 den Mini erlektrisch werden lässt , dieser die selben Werte akzeptiert wie i3 . 
Oder gegen den Wartungsaufwand : nur einzelne Klassen eines Herstellers anstatt jedes Fahrzeug Modell . 

Aber es müssen eh erstmal die Elektro Indistrie voran kommen :)

**Comment by remuslazar** [comment]
Nein, das bringt so auch nichts. Gerade bei dem i3 ist es doch so, dass ältere Modelle 1phasig laden, neuere jedoch 3phasig mit 11kW. DAS müsste man dann auf jeden Fall, wenn schon, so über den Konfigurator ermitteln, sonst macht das ja keinen Sinn. Und dann bei dem Leaf, es gibt ja die 6kW "Doppel-Lader" Option, ältere Tesla's können mit 22kW am AC laden, neuere wiederum nicht (mehr) auch nicht mit der entsprechenden Option.

Wie man siehst, ist das schon sehr komplex, das ist keine einfache Matrix, die dabei heraus kommt. Daher, finde ich, soll der Benutzer besser verstehen, was die Einstellung X und Y bewirken und diese passend zum Fahrzeug und Gusto einmalig einstellen. Mit der neuen Hilfe-Funktion hat man nun auch mehr Möglichkeiten, das auch zu rüber zu bringen.
