### ISSUE TITLE
Doppelte Benachrichtigungen 

### ISSUE THREAD

**Issue by F3000** [remuslazar/EVPlugFinderPublic#92]
Manchmal bekomme ich zwei Benachrichtigungen für einen Standort . 

Bsp.: ich nähere mich von der einen Seite und bekomme 300m vorher eine Nachricht . 

Auch wenn ich nur vorbei fahre bekomme ich 300m danach nochmal eine Nachricht. 

Wäre es möglich da einem timeout einzubauen dass innerhalb von ca. 15 min an dieser Station keine neuen Benachrichtigungen mehr kommen ?

**Comment by secuder** [comment]
Geht mir auch so, und fände ich auch gut (iphone 6plus)

**Comment by remuslazar** [comment]
Ja, das Problem ist bekannt. Allerdings ist es so, dass die App dabei gar nicht involviert ist. Mit anderen Worten: die App bekommt nicht mit, wenn die Notification kommt. Diese registriert lediglich diese "region based" Notifications bei dem Betriebssystem und das Betriebssystem schickt die entsprechend Nachricht, wenn opportun.  Daher kann die App nicht entscheiden, ob die Notification angezeigt wird oder nicht.

Allerdings kann man die Notification auch "one shoot only" registrieren - das heißt, die Notification wird exakt einmal kommen und dann wird der Trigger automatisch gelöscht. Damit wird man das Verhalten so erreichen können. Der Nachteil ist, dass man die App zwischendurch starten muss, sonst wird auch 1 Tag später keine Notification für die jew. Ladestation kommen können.

Daher lasse ich das hier mal offen - das wird vermutlich nicht mehr ins 1.0 schaffen können, weil das Public Release kurz bevor steht.

**Comment by remuslazar** [comment]
@secuder kurze Info: genau dies (und anderes) habe ich im Build 50 implementiert. Das wird aktuell intern beta-getestet, morgen oder übermorgen werde ich das jedoch für alle Tester freigeben.

Es wird dann so sein, dass die Notification pro Ladestation genau nur ein einziges Mal kommt und dann erst frühestens am nächsten Tag wieder.

**Comment by F3000** [comment]
Kann von mir aus auch 12 Stunden sein . Jenachdem wie es dir lieber ist

**Comment by remuslazar** [comment]
24h hat auch technische Gründe, (midnight notification von iOS). Erst mal will ich sehen, wie das angenommen wird.

Algorithmus kann man später noch tunen, z.B. kann die App intelligent entscheiden, ob die Notification erneut getriggert wird, aufgrund der aktuellen Position (z.B. dann wieder triggern, wenn der Benutzer sich um z.B. mind. 2km von der Ladestation entfernt hat - und die App benutzt), damit sichergestellt wird, dass er nicht mehr "im Umkreis" ist. Ist aber alles nicht so ganz trivial zu implementieren und v.a zu testen, deswegen wollte ich mit diesem pragmatischen und simplen Algorithmus sehen, ob das schon mal hilft. Das sind ja schon Edge Cases vermutlich, wo man öfters als 1x/Tag an der gleichen Ladestation lädt und dabei die Notification nutzen wird.

Wenn ich mir so die CheckIns ansehe, so gibt es wirklich selten (0.23%) welche, vom gleichen Benutzer an der gleichen Ladestation am gleichen Tag. Das Problem ist also eher theoretischer Natur. Und die Notification sollte in 1. Linie daran erinnern, den CheckIn zu machen. Oder gibt es dafür auch andere Use-Cases?

**Comment by F3000** [comment]
Danke für deine tolle Ausführung. Du steckst da mehr im technischen Backgroud drin als ich . 

Lass es erstmal so . Wenn mir dazu nochwas auffallen sollte melde ich mich ;)

**Comment by F3000** [comment]
So heute mal mit dem neuen Update getestet . Kommen immer noch zwei . Die zweite kommt noch später als vor dem update .

**Comment by remuslazar** [comment]
@F3000 ich habe das schon im Forum bzw. in den Release Notes beschrieben: hast du für die Ladestation Favoriten-Status dis/enabled? Erst dann greift die neue Einstellung. Kannst du das bitte nochmals testen?

**Comment by remuslazar** [comment]
ich schließe das mal, wenn was ist, @F3000 einfach nochmals öffnen
