### ISSUE TITLE
Telefonnummer anzeigen

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#93]
Es gibt Ladepunkte, bei denen man zuvor anrufen sollte. Auf der GE Seite ist dazu eine Telefonnummer angegeben, die wird in der App nicht angezeigt - was aber schön wäre.

Beispiel https://www.goingelectric.de/stromtankstellen/Deutschland/Lohr/Privater-Ladepunkt-Zum-Muschbach-17/12481/

![e0185654-6729-434e-8899-3beaf87708a5](https://user-images.githubusercontent.com/24484266/32980273-924d9936-cc63-11e7-9c61-0f3b502313cc.png)
![7fcdc316-0b64-4a9b-9758-c09c996c03fa](https://user-images.githubusercontent.com/24484266/32980291-eb82569a-cc63-11e7-9c49-ea56e91030c8.jpeg)

**Comment by remuslazar** [comment]
@secuder siehe https://www.goingelectric.de/forum/ladesaeulen-status/neue-ladestationen-finder-app-fuer-ios-t20449-570.html?hilit=telefonnummer#p625672, dort habe ich elaboriert, warum das nicht möglich ist.

Siehe dazu noch das (offene) Feature-Request für die GE API:

https://www.goingelectric.de/forum/goingelectric-stromtankstellen/offizielle-api-t20221-60.html#p625679
