### ISSUE TITLE
Verschieben der Karte lädt Ladepunkte nicht nach

### ISSUE THREAD

**Issue by wolfijenne** [remuslazar/EVPlugFinderPublic#94]
Durch das Verschieben der Karte wäre es schön, wenn Ladepunkte automatisch nachgeladen werden, da man sonst irgendwann keine Ladepunkte mehr sieht, die eigentlich da wären.
Dies ist gewohnte Usability aus anderen Apps und Webseiten.

**Comment by remuslazar** [comment]
@wolfijenne das wurde ja schon mal im GoingElectric thematisiert. Ich habe dort elaboriert, warum das so ist wie es ist:

https://www.goingelectric.de/forum/ladesaeulen-status/neue-ladestationen-finder-app-fuer-ios-t20449-30.html

Sofern die GE Registry benutzt wird, so wird auch der Radius, wo Ladestationen geladen werden, auf der Karte visualisiert.

**Comment by wolfijenne** [comment]
Danke für die Antwort. Es ist einfach ziemlich ungewohnt, vor allem, da man ja keinen Hinweis darauf hat, ob es nun keine Ladestationen gibt oder ob nur nicht geladen wurde. Vielleicht würde eine Markierung dafür helfen? (Kreis abgedunkelt oder ähnlich).
Was mich bei dem Verhalten intuitiv auch gestört hat ist auch, wenn ich von Hand irgendwo hin navigiere und die Karte vergrössere um mein Ziel zu finden, dann auf den Refresh Knopf drücke, die Karte wieder herauszoomt und ich wiederum von Hand hineinzoomen muss. Ich würde es, wenn das mit dem Reload so bleiben muss, bevorzugen, wenn der Refresh nicht automatisch herauszoomt.

**Comment by remuslazar** [comment]
Es gibt den "long press". Der lädt die Stationen um den Punkt, wo man den Finger hat, neu ohne dabei den Zoom zu verändern.

Es gibt seit dem vorletzten Build eine sog. "App-Hilfe" (Button unten rechts), diese und andere Features sind dort beschrieben.

**Comment by wolfijenne** [comment]
Habe grade den Kreis entdeckt... wenn man tief reinzoomt nimmt man es nicht als Kreis wahr, sondern als Kartenelement. Gut wäre ein Abdunkeln des nicht abgesuchten Bereichs (falls das überhaupt möglich ist).
Der Longpress ist super, damit könntest Du den Refreshbutton auch streichen - ein Element weniger.
Intuitiver wäre aber trotzdem das automatische Laden wie überall anders auch. Aber wenn nicht möglich ist es so auch ok.

**Comment by remuslazar** [comment]
Mit "abdunkeln" hatte ich das damals schon probiert, das war alles nicht gut, deswegen habe ich mich für diese Option entschieden.

Zum automatischen Laden: es gibt, wie schon im verlinkten Beitrag elaboriert, Gründe dafür, es so zu machen. Die App sollte auch mit einer Edge Abdeckung performant sein, da will man nicht unnötig Requests einqueuen nur weil man sich auf der Karte "bewegt" um irgendwas zu suchen. Wenn man die Ladestationen sehen will, so kann man aktiv diese Aktion durchführen und so bleibt auch die Scrolling Performance ideal, weil nicht im Hintergrund Dinge gemacht werden und Pins gerendert werden müssen. Wenn man einen größeren Radius braucht (z.B. iPad), so kann man das in den Settings einstellen. Und wenn man den Filter "nur Schnellladestationen" aktiviert, so wird der Radius auch entsprechend automatisch erhöht, weil das dann Sinn macht.

Und aktuell, da kein Clustering durchgeführt wird (dafür gibt es auch Gründe), gäbe es, insbesondere auf ältere iPhones, Performance Issues, wenn viele Pins auf der Karte gleichzeitig dargestellt werden. Und das wäre ja die Konsequenz vom "automatischen Laden".

iOS 11 bietet hier einige coole neue Maps Features (Clustering), das sind auch Dinge, welche ich im Rahmen eines Updates adressieren möchte. Das Clustering in der Form wie andere das aktuell tun (z.B. NewMotion, ein gutes Beispiel, wie man eine App mit Clustering verhunzen kann) war keine Option, weil das mehr Nachteile als Vorteile hat. Auch in die Richtung gibt es eine Diskussion im GE Forum..

**Comment by IPSCoyote** [comment]
Ich habe sicherlich viel Verständnis für technische Limitierungen (kenne das selbst zur Genüge). Das sollte allerdings kein Argument sein, um durchaus valide (Usability-) Probleme zu ignorieren. Wie @wolfijenne schreibt, ist das Nachladen in anderen Apps üblich und ich würde es auch erwarten. 
Aus meiner Sicht sollte die App den Radius nach dem Verschieben der Karte (ggf. nach einer kurzen Wartesekunde ohne zoom/verschieben) automatisch nachladen (gerne als Option an/abschaltbar). 

Wozu wird die App denn verwendet (werden)? Der 99% Fall dürfte doch die Suche nach einer verfügbaren Ladestation sein. Genau deshalb wird man auf der Karte scrollen. Und genau dieser UseCase verlangt dann, das man manuell nachladen muss. Das sollte aus Usability-Sicht für den Benutzer möglichst vermieden werden. Nur um die Karte zu sehen werden die meisten doch wohl eher Google/Apple Maps verwenden. 

Nichts, was jetzt sofort für eine 1.0 sein muss. Aber zu einer "runden" App gehört das aus meiner Sicht dazu.
