### ISSUE TITLE
Ljubljana ist nur unter Laibach zu finden

### ISSUE THREAD

**Issue by wolfijenne** [remuslazar/EVPlugFinderPublic#95]
seltsame Lokalisierung, keine Ahnung woher das kommt und ob man das irgendwo einstellen kann.
Minor Issue

**Comment by wolfijenne** [comment]
Wenn man Lubljana richtig schreibt, gehts besser :)

**Comment by remuslazar** [comment]
Ich wollte gerade schreiben, das hat mit der Lokalisierung an sich nichts zu tun..
