### ISSUE TITLE
Feature Request: Feedback an GE

### ISSUE THREAD

**Issue by wolfijenne** [remuslazar/EVPlugFinderPublic#96]
In einem zukünftigen Release:
Feedback zu Ladestationen (Funktionsstörungen, erfolgreiche Lademeldungen, Bilder Upload, Neue Ladestationen) an GE mit GE Login. Keine Ahnung ob GE das überhaupt erlaubt oder nicht. Aber dann würde es GE perfekt ergänzen und die Datenqualität sehr hoch halten.

**Comment by remuslazar** [comment]
Macht keinen Sinn, hier dafür einen Issue aufzumachen. Die App nutzt schon jetzt maximal alle Möglichkeiten, die im Rahmen der API angeboten werden (und sogar darüber hinaus). Sollte die GE API entsprechenden Erweiterungen anbieten, so wird die App das schon nachziehen, da es sich seit über 1 Jahr in die Richtung nichts getan hat, ist es nicht sehr wahrscheinlich, dass sich das ändern wird.

Zu der Check-In Funktion habe ich hier alles dokumentiert:

https://github.com/remuslazar/EVPlugFinderPublic/wiki/Check-In-Feature

und hier habe ich auch bereits dokumentiert, welche Erweiterungen in die Richtung geplant sind:

https://github.com/remuslazar/EVPlugFinderPublic/wiki/Check-in-Feature-Reloaded

**Comment by wolfijenne** [comment]
Danke für die Links... ist lehrreich :)
Zur Namensgebung von Checkin: Vielleicht History? Persönlich finde ich weitere Angaben wie Ladezeit, Lademenge und kosten unnötig, aber vielleicht sehen das Andere ja eben anders.
So was ähnliches hab ich mir gedacht. Wäre für GE eigentlich schon wichtig, sonst kommen aktuelle Infos nie in die Mutter DB.
