### ISSUE TITLE
Datenquellen sollten parallel angezeigt werden (nicht entweder/oder)

### ISSUE THREAD

**Issue by IPSCoyote** [remuslazar/EVPlugFinderPublic#98]
Ich verstehe nicht so ganz, wieso man bei einer "übergreifenden" App (was super ist/wäre) sich in den Einstellungen für eine Datenquelle (GE/OCM) entscheiden muss.

Konkret: In meinem Umfeld gibt es Säulen die nur in GoingElectric gelistet sind, andere sind dagegen nur auf OCM aufgeführt. Somit habe ich keinen Gesamtüberblick sondern muss manuell wechseln. Besonders ärgerlich, wenn man sich nicht auskennt.
Kann man hier nicht einfach auf beide Quellen zugreifen und diese kombiniert (ggf. mit einer Präferenz) anzeigen?

**Comment by remuslazar** [comment]
@IPSCoyote diese Gedanken gab es auch von mir (und andere), es gibt jedoch einige Gründe, v.a. technischer Natur, warum das nicht so einfach realisierbar ist. Da die Ladestationen (zum. im GE Verzeichnis) nicht mit einem eindeutigen Identifier versehen sind, lässt sich ein "Merge" nicht automatisiert durchführen und das würde sonst dazu führen, dass man sehr viele Doubletten hätte, was dann mehr Nachteile als Vorteile bringt.

Außerdem ist die Struktur der Daten heterogen und so sind die Filter Kriterien pro Quelle unterschiedliche. z.B. erlaubt die OCM Quelle keine sog. "Radius-Suche", dort werden einfach die Anzahl der Ergebnisse limitiert, bei GE ist das genau anders herum.

Ich will nicht ausschließen, dass sich mittelfristig in diese Richtung was tun wird, aktuell ist es jedoch aus einigen Gründen (o.g. und weitere) nicht möglich.

**Comment by IPSCoyote** [comment]
Dann habe ich aber trotzdem was interessantes festgestellt:

- Erstmaliges Öffnen (nach Schliessen der App): Es werden viele Ladepunkte (GoingElectric) angezeigt
- Wechsel in Einstellungen auf OCM -> es verschwinden einige
- Wechsel zurück auf GE -> es werden wieder die GE Punkte angezeigt, **aber nicht alle!**

Da scheinen Ladepunkte beim Wechsel in den Einstellungen (ohne Neustart der App) verloren zu gehen.

Zum Ursprungsthema: Dann solle man ggf. einen Toggle zum Wechsel der Datenbasis anbieten (bei mehreren Quellen dann durchschalten), damit man als User wenigstens mit einem Tipp die Quelle (somit schnell) wechseln kann.

**Comment by remuslazar** [comment]
@IPSCoyote danke für die Info, ich versuche das zu reproduzieren. Wenn das so ist, würde ich es auch als Bug sehen. Was bedeutet konkret "schließen der App"? Force-Kill mit Swipe nach oben?

Wechsel der Datenquelle muss man eigentlich recht selten vornehmen (z.B. Ausland). In Deutschland ist man ja gut mit GE bedient. Gibt es konkrete Beispiele, wo die Information im OCM im DACH-Raum vollständiger ist?

Wechsel der Datenquelle geht einfach über die Settings, dazu habe ich in der Filter View ein Link eingefügt, das geht doch recht schnell (unter 5 Sekunden).

**Comment by IPSCoyote** [comment]
Ja, Force-Kill (also einfach das die App geschlossen ist wie nach einem Reboot).

Bzgl. des Wechsels finde ich halt jeden vermeidbaren "Klick" hilfreich (wobei natürlich nichts direkt machbar sein muss, das man nur alle paar Jahre braucht) ?
