### ISSUE TITLE
Pin-Farbe abhängig von Datenquelle

### ISSUE THREAD

**Issue by secuder** [remuslazar/EVPlugFinderPublic#99]
Die in issue #90 erarbeitete Lösung zur Farbcodierung der Pins funktioniert nur in Verbindung mit der GE Datenquelle. Bei Verwendung von OCM werden die Pins auch bei gleicher KW Angabe anders dargestellt

**Comment by remuslazar** [comment]
@secuder bei OCM gibt es diese Klassifizierung (level1,2,3) bereits, die wird dann auch für die Farbe genutzt. Nur bei GE gibt es diese Leistungsklasse nicht, diese wird mit der (mittlerweile recht intelligenten Logik) berechnet.

Ich lasse das daher offen, evtl. sollte man das in der Tat konsolidieren.

**Comment by secuder** [comment]
die OCM Logik ist aber anders und deutlich schlechter. So werden 3,6kW Ladestellen in der gleichen Farbe wie eine 11kW Ladestelle dargestellt - und das, obwohl letztere 3-mal so schnell lädt. Das ist ja gerade das tolle an der in Verbindung mit der Goingelektric-Datenbank realisierten Logik, dass dieser sehr wichtige Unterschied (siehe Issue #90) sichtbar wird.

Insofern: Ich plädiere ganz unbedingt zu einer Konsolidierung hin zu der Farben-Berechnung nach "GE-Logik"
